// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ParseIssue describes one non-fatal problem found while parsing. Rows that
 * miss a Required key are dropped; the issue records why.
 */
export interface ParseIssue {
    "LineNo": number;
    "Key": string;
    "Message": string;
}

/**
 * PreviewRow is one parsed row as the template-testing surface shows it: the
 * produced line number, the source data row it came from, the semantic values,
 * and the duplicate-detection fingerprint the import would compute.
 */
export interface PreviewRow {
    "LineNo": number;
    "SourceRow": number;
    "Values": { [_ in string]?: string } | null;
    "Fingerprint": string;
}

/**
 * TemplatePreview is the result of running a template against sample data
 * without touching any store: the first rows plus every issue found, with the
 * counts needed to judge the mapping beyond the truncated sample.
 */
export interface TemplatePreview {
    "Rows": PreviewRow[] | null;
    "Issues": ParseIssue[] | null;

    /**
     * TotalRows is how many rows the parse produced before limit truncation.
     */
    "TotalRows": number;

    /**
     * DroppedRows counts source rows (or split candidates) the parse
     * discarded because a Required key was empty or the splitSkuQuantity blob
     * could not be expanded.
     */
    "DroppedRows": number;
}
