// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as alignment$0 from "./alignment/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * DocumentTypeInfo is one row of the closed document-type catalog: the key
 * stored on templates, the direction it locks, and the platform kind that may
 * own such templates.
 */
export interface DocumentTypeInfo {
    "Key": string;
    "Direction": string;
    "PlatformKind": string;
}

/**
 * ExceptionView is one entitlement exception joined with the display fields
 * the wave screen needs: the member behind the instance and the product the
 * exception grants.
 */
export interface ExceptionView {
    "ID": number;
    "InstanceID": number;
    "CustomerName": string;
    "ProductItemID": number;
    "ProductName": string;
    "Quantity": number;
    "Note": string;
}

/**
 * ExportFileResult reports a rendered export: the updated order, the absolute
 * file path, and the rows that were written.
 */
export interface ExportFileResult {
    "Order": domain$0.SupplierOrder;
    "Path": string;
    "Rows": ({ [_ in string]?: string } | null)[] | null;
}

export interface GenerateFactoryOrderResult {
    "Order": domain$0.SupplierOrder;
    "Lines": domain$0.SupplierOrderLine[] | null;
}

export interface HomeBuckets {
    "Unassigned": number;
    "DuplicateAsk": number;
    "AlignmentConflict": number;
    "IdentityUnattached": number;
    "PendingRevisions": number;
    "BlockedResults": number;
    "WritebackFailed": number;
    "ResidualClose": number;

    /**
     * RevisionFrozenConflicts warns that applied revisions replaced lines
     * whose results were already frozen into factory orders.
     */
    "RevisionFrozenConflicts": number;
    "RecentWaves": domain$0.Wave[] | null;
}

/**
 * ImportCarrierMappingsResult summarizes a carrier table import.
 */
export interface ImportCarrierMappingsResult {
    "Created": number;
    "Updated": number;
    "Skipped": number;
    "Issues": alignment$0.ParseIssue[] | null;
}

/**
 * ImportFileResult reports what a file import produced: the document, the
 * facts and lines that landed, duplicate observations, and parse issues.
 */
export interface ImportFileResult {
    "Document": domain$0.InputDocument;
    "FactsCreated": number;
    "LinesCreated": number;
    "Duplicates": domain$0.DuplicateObservation[] | null;
    "Issues": alignment$0.ParseIssue[] | null;
}

/**
 * ImportShipmentFileResult summarizes a shipment-return import.
 */
export interface ImportShipmentFileResult {
    "Imported": number;
    "Skipped": SkippedShipment[] | null;
    "Shipments": domain$0.Shipment[] | null;
    "Issues": alignment$0.ParseIssue[] | null;
}

export interface InboxRow {
    "Line": domain$0.InputFactLine;
    "Fact": domain$0.InputFact;
    "Document": domain$0.InputDocument | null;
    "Assigned": boolean;
    "Unaligned": boolean;
    "Unattached": boolean;

    /**
     * RevisionPending marks rows of a revision fact awaiting an apply or
     * dismiss decision; they are visible but not assignable.
     */
    "RevisionPending": boolean;

    /**
     * AliasID resolves the line's external SKU to its product alias, when
     * one exists, so alignment actions can target it.
     */
    "AliasID": number | null;
}

export interface IngestDocumentResult {
    "Document": domain$0.InputDocument;
    "Duplicates": domain$0.DuplicateObservation[] | null;
}

export interface IngestFactInput {
    "Kind": string;
    "StableExternalID": string;
    "IdentityType": string;
    "IdentityValue": string;
    "MembershipLevel": string;
    "SourceDocumentNo": string;
    "SourceCreatedAt": string | null;
    "CustomerProfileID": number | null;

    /**
     * DisplayName names the customer profile created for a not-yet-known
     * identity (customer.display_name); empty falls back to the identity
     * value or the recipient name.
     */
    "DisplayName": string;

    /**
     * Recipient is the recipient data the row carried (recipient.*). It is
     * written to the resolved customer profile as an address; when the row
     * has no identity it also decides which profile the fact belongs to.
     */
    "Recipient": domain$0.AddressSnapshot | null;
    "ExtraData": string;
    "Lines": IngestLine[] | null;
}

export interface IngestLine {
    "SourceLineNo": number;
    "ExternalSKU": string;
    "ExternalTitle": string;
    "ExternalSpec": string;
    "Quantity": number;
}

/**
 * InstanceView is one entitlement instance with the member-facing display
 * fields: customer name and a platform identity summary.
 */
export interface InstanceView {
    "ID": number;
    "CustomerName": string;
    "PlatformIdentity": string;
    "MembershipLevel": string;
}

export interface ProductTotal {
    "ProductID": number;
    "Name": string;
    "Quantity": number;
}

export interface ResultView {
    "Result": domain$0.FulfillmentResult;
    "WorkState": domain$0.WorkState;
    "Blocks": domain$0.BlockReason[] | null;
    "InFactory": boolean;
    "Shipped": boolean;
    "WritebackFailed": boolean;
}

/**
 * SampleFileInfo describes a tabular file before any mapping is applied: its
 * format, the selectable xlsx sheets, the first raw records (the first one is
 * the candidate header row), and the total record count.
 */
export interface SampleFileInfo {
    "Format": string;
    "Sheets": string[] | null;
    "Records": (string[] | null)[] | null;
    "Total": number;
}

/**
 * SkippedShipment records why one shipment-return row did not import.
 */
export interface SkippedShipment {
    "LineNo": number;
    "TrackingID": string;
    "Reason": string;
}

/**
 * WritebackFileResult reports one writeback export: the written file's
 * absolute path.
 */
export interface WritebackFileResult {
    "Path": string;
}
