export { default as FieldMappingEditor } from './FieldMappingEditor.vue'
export type { CatalogImageLayoutValue } from './types'
export type { FieldMappingDestField, FieldMappingMode, FieldMappingValue } from './types'
export { parseMappingRules, serializeMappingRules } from './types'
export { applyMapping, validateDestFieldValue } from './previewTransform'
export type { MappedPreviewRow } from './previewTransform'
