// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCarrierMapping(arg1) {
  return window['go']['main']['ChannelSyncController']['CreateCarrierMapping'](arg1);
}

export function CreateChannelSyncJob(arg1) {
  return window['go']['main']['ChannelSyncController']['CreateChannelSyncJob'](arg1);
}

export function DeleteCarrierMapping(arg1) {
  return window['go']['main']['ChannelSyncController']['DeleteCarrierMapping'](arg1);
}

export function ExecuteChannelSyncJob(arg1) {
  return window['go']['main']['ChannelSyncController']['ExecuteChannelSyncJob'](arg1);
}

export function ListCarrierMappings(arg1) {
  return window['go']['main']['ChannelSyncController']['ListCarrierMappings'](arg1);
}

export function ListChannelSyncJobsByWave(arg1) {
  return window['go']['main']['ChannelSyncController']['ListChannelSyncJobsByWave'](arg1);
}

export function ListConnectorCapabilities() {
  return window['go']['main']['ChannelSyncController']['ListConnectorCapabilities']();
}

export function ListIntegrationProfiles() {
  return window['go']['main']['ChannelSyncController']['ListIntegrationProfiles']();
}

export function PlanChannelClosure(arg1) {
  return window['go']['main']['ChannelSyncController']['PlanChannelClosure'](arg1);
}

export function RecordChannelClosureDecision(arg1) {
  return window['go']['main']['ChannelSyncController']['RecordChannelClosureDecision'](arg1);
}

export function RetryChannelSyncJob(arg1) {
  return window['go']['main']['ChannelSyncController']['RetryChannelSyncJob'](arg1);
}
