// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function AddCustomerIdentity(arg1:dto.CreateCustomerIdentityInput):Promise<dto.CustomerIdentityDTO>;

export function CreateCustomerProfile(arg1:dto.CreateCustomerProfileInput):Promise<dto.CustomerProfileDTO>;

export function DeleteCustomerIdentity(arg1:number):Promise<void>;

export function DeleteCustomerProfile(arg1:number):Promise<void>;

export function DismissMergeSuggestion(arg1:number):Promise<void>;

export function GetCustomerFulfillmentHistory(arg1:number):Promise<Array<dto.CustomerFulfillmentHistoryRowDTO>>;

export function GetCustomerProfile(arg1:number):Promise<dto.CustomerProfileDTO>;

export function GetMergeSuggestions():Promise<Array<dto.MergeSuggestionDTO>>;

export function GetSettings():Promise<dto.SystemSettingsDTO>;

export function ListCustomerProfiles(arg1:string,arg2:string,arg3:boolean):Promise<Array<dto.CustomerProfileDTO>>;

export function SaveSettings(arg1:dto.SystemSettingsDTO):Promise<void>;

export function UpdateCustomerProfile(arg1:dto.UpdateCustomerProfileInput):Promise<dto.CustomerProfileDTO>;
