// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function BindTemplateToProfile(arg1:dto.BindTemplateToProfileInput):Promise<dto.ProfileTemplateBindingDTO>;

export function CreateDocumentTemplate(arg1:dto.CreateDocumentTemplateInput):Promise<dto.DocumentTemplateDTO>;

export function GetDefaultTemplateForProfile(arg1:number,arg2:string):Promise<dto.DocumentTemplateDTO>;

export function ListBindingsByProfile(arg1:number):Promise<Array<dto.ProfileTemplateBindingDTO>>;

export function ListDocumentTemplates():Promise<Array<dto.DocumentTemplateDTO>>;
