// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PickCSVFile():Promise<string>;

export function PickZIPFile():Promise<string>;

export function SaveZoom(arg1:number):Promise<void>;
