// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListCustomerIdentityPlatforms() {
  return window['go']['main']['ListPaginationController']['ListCustomerIdentityPlatforms']();
}

export function ListCustomerProfilesPage(arg1) {
  return window['go']['main']['ListPaginationController']['ListCustomerProfilesPage'](arg1);
}

export function ListDemandInboxRowsPage(arg1) {
  return window['go']['main']['ListPaginationController']['ListDemandInboxRowsPage'](arg1);
}

export function ListProductMastersPage(arg1) {
  return window['go']['main']['ListPaginationController']['ListProductMastersPage'](arg1);
}

export function ListShipmentsByWavePage(arg1) {
  return window['go']['main']['ListPaginationController']['ListShipmentsByWavePage'](arg1);
}
