// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function UndoCustomerMerge(arg1:dto.UndoCustomerMergeInput):Promise<dto.UndoCustomerMergeResult>;
