// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileSystemController exposes a single "reveal a file in its containing
 * folder" Wails binding. Self-contained: pure OS call, no repo/DB dependency,
 * mirroring the other single-purpose controllers (e.g. WorkspaceController).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * GetDataDir exposes the resolved data directory path to the frontend.
 */
export function GetDataDir(): $CancellablePromise<string> {
    return $Call.ByID(2287571589);
}

/**
 * RevealInFolder opens the OS file manager with the given file selected (or,
 * on platforms without file-select support, opens its containing directory).
 * Only paths under the application data directory are allowed (catalog-import
 * extracts live at data/tmp/catalog-import and are covered by that root).
 */
export function RevealInFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(965686824, path);
}
