// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as alignment$0 from "../app/alignment/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export function AddException(e: domain$0.EntitlementException): $CancellablePromise<void> {
    return $Call.ByID(2429566814, e);
}

export function ApplyRevision(factID: number): $CancellablePromise<void> {
    return $Call.ByID(2776315647, factID);
}

export function AssignLines(waveID: number, lineIDs: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(4014885938, waveID, lineIDs);
}

export function AttachIdentity(identityID: number, customerID: number): $CancellablePromise<void> {
    return $Call.ByID(500335737, identityID, customerID);
}

export function CloseWave(id: number, result: string, note: string): $CancellablePromise<void> {
    return $Call.ByID(2005805899, id, result, note);
}

export function CreateAddress(a: domain$0.RecipientAddress): $CancellablePromise<domain$0.RecipientAddress | null> {
    return $Call.ByID(3386754674, a);
}

export function CreateAlias(a: domain$0.ProductAlias): $CancellablePromise<domain$0.ProductAlias | null> {
    return $Call.ByID(842632950, a);
}

export function CreateBundleComponent(comp: domain$0.ProductBundleComponent): $CancellablePromise<void> {
    return $Call.ByID(953010961, comp);
}

export function CreateCarrierMapping(m: domain$0.CarrierMapping): $CancellablePromise<domain$0.CarrierMapping | null> {
    return $Call.ByID(3703026556, m);
}

export function CreateCustomer(name: string, notes: string): $CancellablePromise<domain$0.CustomerProfile | null> {
    return $Call.ByID(2665146170, name, notes);
}

export function CreateGrant(waveID: number, customerID: number, productID: number, qty: number): $CancellablePromise<domain$0.FulfillmentResult | null> {
    return $Call.ByID(2634733640, waveID, customerID, productID, qty);
}

export function CreatePlatform(p: domain$0.Platform): $CancellablePromise<void> {
    return $Call.ByID(2682431553, p);
}

export function CreateProduct(p: domain$0.ProductItem): $CancellablePromise<domain$0.ProductItem | null> {
    return $Call.ByID(3727361817, p);
}

/**
 * CreateTemplate stores a new active (user) template at version 1.
 */
export function CreateTemplate(t: domain$0.TemplateConfig): $CancellablePromise<domain$0.TemplateConfig | null> {
    return $Call.ByID(3124762364, t);
}

export function CreateWave(name: string, notes: string): $CancellablePromise<domain$0.Wave | null> {
    return $Call.ByID(1103245883, name, notes);
}

export function DecideDuplicate(id: number, accept: boolean): $CancellablePromise<void> {
    return $Call.ByID(552578027, id, accept);
}

export function DeleteCarrierMapping(id: number): $CancellablePromise<void> {
    return $Call.ByID(513958303, id);
}

export function DeleteException(id: number): $CancellablePromise<void> {
    return $Call.ByID(3366201354, id);
}

export function DeleteQuantitySplitRule(id: number): $CancellablePromise<void> {
    return $Call.ByID(407595834, id);
}

export function DeleteRule(id: number): $CancellablePromise<void> {
    return $Call.ByID(2144276463, id);
}

/**
 * DeleteTemplate removes a user template; built-in rows are refused.
 */
export function DeleteTemplate(id: number): $CancellablePromise<void> {
    return $Call.ByID(1413120559, id);
}

export function DismissRevision(factID: number): $CancellablePromise<void> {
    return $Call.ByID(2970823171, factID);
}

/**
 * DocumentTypeCatalog returns the closed document-type set with the direction
 * and platform kind each type locks.
 */
export function DocumentTypeCatalog(): $CancellablePromise<app$0.DocumentTypeInfo[] | null> {
    return $Call.ByID(61708502);
}

export function EnsureBuiltinPlatforms(): $CancellablePromise<void> {
    return $Call.ByID(919068065);
}

/**
 * EnsureBuiltinTemplates re-seeds the read-only template catalog; startup
 * runs it after EnsureBuiltinPlatforms.
 */
export function EnsureBuiltinTemplates(): $CancellablePromise<void> {
    return $Call.ByID(3688566322);
}

export function ExportFactoryOrder(orderID: number): $CancellablePromise<domain$0.SupplierOrder | null> {
    return $Call.ByID(2211263098, orderID);
}

export function ExportFactoryOrderFile(orderID: number): $CancellablePromise<app$0.ExportFileResult | null> {
    return $Call.ByID(4248829468, orderID);
}

/**
 * ExportWritebackFile writes one writeback item's stored payload to the
 * exports directory and returns the absolute path.
 */
export function ExportWritebackFile(writebackID: number): $CancellablePromise<app$0.WritebackFileResult | null> {
    return $Call.ByID(1579990378, writebackID);
}

export function GenerateFactoryOrder(waveID: number, factoryID: number): $CancellablePromise<app$0.GenerateFactoryOrderResult | null> {
    return $Call.ByID(3862633291, waveID, factoryID);
}

/**
 * GenerateFactoryOrderForResults submits only the selected fulfillment
 * results; resultIDs nil means the whole wave, an explicitly empty selection
 * submits nothing (ErrNothingToSubmit).
 */
export function GenerateFactoryOrderForResults(waveID: number, factoryID: number, resultIDs: number[] | null): $CancellablePromise<app$0.GenerateFactoryOrderResult | null> {
    return $Call.ByID(1107514588, waveID, factoryID, resultIDs);
}

export function GenerateWritebacks(factID: number): $CancellablePromise<domain$0.ChannelWritebackItem[] | null> {
    return $Call.ByID(3267202336, factID);
}

export function GetCustomer(id: number): $CancellablePromise<domain$0.CustomerProfile | null> {
    return $Call.ByID(1030978122, id);
}

export function GetSettings(): $CancellablePromise<domain$0.AppSettings | null> {
    return $Call.ByID(236563183);
}

export function GetTemplate(id: number): $CancellablePromise<domain$0.TemplateConfig | null> {
    return $Call.ByID(3533252524, id);
}

export function GetWave(id: number): $CancellablePromise<domain$0.Wave | null> {
    return $Call.ByID(3293238731, id);
}

export function Home(): $CancellablePromise<app$0.HomeBuckets> {
    return $Call.ByID(1318569521);
}

/**
 * ImportCarrierMappings loads a source platform's carrier table from a file;
 * nameHeader and codeHeader name the columns carrying the carrier description
 * and the platform's carrier code.
 */
export function ImportCarrierMappings(platformID: number, filePath: string, nameHeader: string, codeHeader: string): $CancellablePromise<app$0.ImportCarrierMappingsResult | null> {
    return $Call.ByID(2614951950, platformID, filePath, nameHeader, codeHeader);
}

export function ImportFile(platformID: number, templateID: number, filePath: string): $CancellablePromise<app$0.ImportFileResult | null> {
    return $Call.ByID(776281197, platformID, templateID, filePath);
}

export function ImportShipment(trackingID: string, trackingNo: string, carrierCode: string, carrierName: string, qty: number): $CancellablePromise<domain$0.Shipment | null> {
    return $Call.ByID(4000120241, trackingID, trackingNo, carrierCode, carrierName, qty);
}

/**
 * ImportShipmentFile imports a factory shipment return through the given
 * active shipment_return template of the factory platform.
 */
export function ImportShipmentFile(platformID: number, templateID: number, filePath: string): $CancellablePromise<app$0.ImportShipmentFileResult | null> {
    return $Call.ByID(2512714711, platformID, templateID, filePath);
}

export function IngestDocument(doc: domain$0.InputDocument, facts: app$0.IngestFactInput[] | null): $CancellablePromise<app$0.IngestDocumentResult | null> {
    return $Call.ByID(3044417039, doc, facts);
}

/**
 * InspectSampleFile returns a file's raw records (first row = candidate
 * header), its format, and xlsx sheet names, without applying any mapping.
 */
export function InspectSampleFile(filePath: string, sheetName: string, limit: number): $CancellablePromise<app$0.SampleFileInfo | null> {
    return $Call.ByID(1883210382, filePath, sheetName, limit);
}

export function ListAddresses(customerID: number): $CancellablePromise<domain$0.RecipientAddress[] | null> {
    return $Call.ByID(3107385986, customerID);
}

export function ListAliases(productID: number): $CancellablePromise<domain$0.ProductAlias[] | null> {
    return $Call.ByID(1069351806, productID);
}

export function ListCarrierMappings(platformID: number): $CancellablePromise<domain$0.CarrierMapping[] | null> {
    return $Call.ByID(2285131629, platformID);
}

export function ListCustomers(): $CancellablePromise<domain$0.CustomerProfile[] | null> {
    return $Call.ByID(2808916827);
}

/**
 * ListEntitlementInstances returns the wave's membership instances with
 * customer name and platform identity summary.
 */
export function ListEntitlementInstances(waveID: number): $CancellablePromise<app$0.InstanceView[] | null> {
    return $Call.ByID(3081021051, waveID);
}

/**
 * ListExceptions returns the wave's entitlement exceptions joined with
 * customer and product display names.
 */
export function ListExceptions(waveID: number): $CancellablePromise<app$0.ExceptionView[] | null> {
    return $Call.ByID(645974512, waveID);
}

export function ListInboxRows(): $CancellablePromise<app$0.InboxRow[] | null> {
    return $Call.ByID(1295818375);
}

export function ListPlatforms(): $CancellablePromise<domain$0.Platform[] | null> {
    return $Call.ByID(2540837062);
}

export function ListProducts(): $CancellablePromise<domain$0.ProductItem[] | null> {
    return $Call.ByID(2582544942);
}

export function ListQuantitySplitRules(waveID: number): $CancellablePromise<domain$0.QuantitySplitRule[] | null> {
    return $Call.ByID(2275288004, waveID);
}

export function ListResultViews(waveID: number): $CancellablePromise<app$0.ResultView[] | null> {
    return $Call.ByID(294650047, waveID);
}

export function ListRules(waveID: number): $CancellablePromise<domain$0.EntitlementRule[] | null> {
    return $Call.ByID(509006269, waveID);
}

export function ListSupplierOrderLines(orderID: number): $CancellablePromise<domain$0.SupplierOrderLine[] | null> {
    return $Call.ByID(3453083161, orderID);
}

export function ListSupplierOrders(waveID: number): $CancellablePromise<domain$0.SupplierOrder[] | null> {
    return $Call.ByID(351495459, waveID);
}

/**
 * ListTemplates returns built-in and user templates; the Builtin flag tells
 * them apart.
 */
export function ListTemplates(): $CancellablePromise<domain$0.TemplateConfig[] | null> {
    return $Call.ByID(1772605357);
}

export function ListWaves(): $CancellablePromise<domain$0.Wave[] | null> {
    return $Call.ByID(1984537928);
}

/**
 * ListWritebacksByWave returns the writeback items behind the wave's facts,
 * ordered by item id.
 */
export function ListWritebacksByWave(waveID: number): $CancellablePromise<domain$0.ChannelWritebackItem[] | null> {
    return $Call.ByID(3983613015, waveID);
}

/**
 * MarkWritebackFailed records a failed channel writeback attempt for one
 * parcel; the retry counter advances and the error text is kept (truncated).
 */
export function MarkWritebackFailed(writebackID: number, errMsg: string): $CancellablePromise<void> {
    return $Call.ByID(2193912976, writebackID, errMsg);
}

/**
 * MarkWritebackSent records a successful channel writeback for one parcel.
 */
export function MarkWritebackSent(writebackID: number): $CancellablePromise<void> {
    return $Call.ByID(811966835, writebackID);
}

export function MoveLines(lineIDs: number[] | null, targetWaveID: number): $CancellablePromise<void> {
    return $Call.ByID(1288593526, lineIDs, targetWaveID);
}

export function NamedTransformers(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3655086871);
}

/**
 * PreviewMapping runs an unsaved mapping JSON against a sample file.
 */
export function PreviewMapping(mappingJSON: string, documentType: string, filePath: string, limit: number): $CancellablePromise<alignment$0.TemplatePreview | null> {
    return $Call.ByID(4093893780, mappingJSON, documentType, filePath, limit);
}

/**
 * PreviewTemplate runs a saved template (built-in ones included) against a
 * sample file.
 */
export function PreviewTemplate(templateID: number, filePath: string, limit: number): $CancellablePromise<alignment$0.TemplatePreview | null> {
    return $Call.ByID(387600756, templateID, filePath, limit);
}

export function ProductTotals(waveID: number): $CancellablePromise<app$0.ProductTotal[] | null> {
    return $Call.ByID(3126250874, waveID);
}

export function ReopenWave(id: number): $CancellablePromise<void> {
    return $Call.ByID(1961269718, id);
}

export function SaveSettings(s: domain$0.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(2722186054, s);
}

export function SemanticDictionary(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1871193874);
}

export function SetResultAddress(resultID: number, addressID: number): $CancellablePromise<void> {
    return $Call.ByID(2828119021, resultID, addressID);
}

export function UpdateAlias(aliasID: number, productItemID: number): $CancellablePromise<void> {
    return $Call.ByID(1951810001, aliasID, productItemID);
}

export function UpdateCarrierMapping(m: domain$0.CarrierMapping): $CancellablePromise<domain$0.CarrierMapping | null> {
    return $Call.ByID(4064628333, m);
}

export function UpdateCustomer(cust: domain$0.CustomerProfile): $CancellablePromise<void> {
    return $Call.ByID(757493027, cust);
}

/**
 * UpdateTemplate edits a user template in place and advances its version;
 * built-in rows are refused.
 */
export function UpdateTemplate(t: domain$0.TemplateConfig): $CancellablePromise<domain$0.TemplateConfig | null> {
    return $Call.ByID(411689605, t);
}

export function UpsertQuantitySplitRule(rule: domain$0.QuantitySplitRule): $CancellablePromise<void> {
    return $Call.ByID(1574475242, rule);
}

export function UpsertRule(rule: domain$0.EntitlementRule): $CancellablePromise<domain$0.EntitlementRule | null> {
    return $Call.ByID(3905115839, rule);
}

export function VoidFactoryOrder(orderID: number): $CancellablePromise<void> {
    return $Call.ByID(481319606, orderID);
}
