// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchBindAddressToLines(arg1) {
  return window['go']['controller']['AddressController']['BatchBindAddressToLines'](arg1);
}

export function BindAddressToLine(arg1) {
  return window['go']['controller']['AddressController']['BindAddressToLine'](arg1);
}

export function BindDefaultAddressesForWave(arg1) {
  return window['go']['controller']['AddressController']['BindDefaultAddressesForWave'](arg1);
}

export function CreateAddress(arg1) {
  return window['go']['controller']['AddressController']['CreateAddress'](arg1);
}

export function DeleteAddress(arg1) {
  return window['go']['controller']['AddressController']['DeleteAddress'](arg1);
}

export function GetAddress(arg1) {
  return window['go']['controller']['AddressController']['GetAddress'](arg1);
}

export function ListAddressesByProfile(arg1) {
  return window['go']['controller']['AddressController']['ListAddressesByProfile'](arg1);
}

export function UnbindAddressFromLine(arg1) {
  return window['go']['controller']['AddressController']['UnbindAddressFromLine'](arg1);
}

export function UpdateAddress(arg1) {
  return window['go']['controller']['AddressController']['UpdateAddress'](arg1);
}
