// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchRecordAdjustments(arg1) {
  return window['go']['controller']['AdjustmentController']['BatchRecordAdjustments'](arg1);
}

export function ListAdjustmentsByWave(arg1) {
  return window['go']['controller']['AdjustmentController']['ListAdjustmentsByWave'](arg1);
}

export function RecordAdjustment(arg1) {
  return window['go']['controller']['AdjustmentController']['RecordAdjustment'](arg1);
}
