// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function GetCustomerResolutionFeaturePolicy():Promise<dto.CustomerResolutionFeaturePolicyDTO>;

export function UpdateCustomerResolutionFeaturePolicy(arg1:dto.UpdateCustomerResolutionFeaturePolicyInput):Promise<dto.CustomerResolutionFeaturePolicyDTO>;
