// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomerIdentity(arg1) {
  return window['go']['controller']['CustomerProfileController']['AddCustomerIdentity'](arg1);
}

export function CreateCustomerProfile(arg1) {
  return window['go']['controller']['CustomerProfileController']['CreateCustomerProfile'](arg1);
}

export function DeleteCustomerIdentity(arg1) {
  return window['go']['controller']['CustomerProfileController']['DeleteCustomerIdentity'](arg1);
}

export function DeleteCustomerProfile(arg1) {
  return window['go']['controller']['CustomerProfileController']['DeleteCustomerProfile'](arg1);
}

export function DismissMergeSuggestion(arg1) {
  return window['go']['controller']['CustomerProfileController']['DismissMergeSuggestion'](arg1);
}

export function GetCustomerFulfillmentHistory(arg1) {
  return window['go']['controller']['CustomerProfileController']['GetCustomerFulfillmentHistory'](arg1);
}

export function GetCustomerProfile(arg1) {
  return window['go']['controller']['CustomerProfileController']['GetCustomerProfile'](arg1);
}

export function GetMergeSuggestions() {
  return window['go']['controller']['CustomerProfileController']['GetMergeSuggestions']();
}

export function GetSettings() {
  return window['go']['controller']['CustomerProfileController']['GetSettings']();
}

export function ListCustomerNameObservations(arg1) {
  return window['go']['controller']['CustomerProfileController']['ListCustomerNameObservations'](arg1);
}

export function ListCustomerProfileOrigins(arg1) {
  return window['go']['controller']['CustomerProfileController']['ListCustomerProfileOrigins'](arg1);
}

export function ListCustomerProfiles(arg1, arg2, arg3) {
  return window['go']['controller']['CustomerProfileController']['ListCustomerProfiles'](arg1, arg2, arg3);
}

export function PinCustomerDisplayName(arg1) {
  return window['go']['controller']['CustomerProfileController']['PinCustomerDisplayName'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['controller']['CustomerProfileController']['SaveSettings'](arg1);
}

export function UnpinCustomerDisplayName(arg1) {
  return window['go']['controller']['CustomerProfileController']['UnpinCustomerDisplayName'](arg1);
}

export function UpdateCustomerProfile(arg1) {
  return window['go']['controller']['CustomerProfileController']['UpdateCustomerProfile'](arg1);
}
