// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDataDir() {
  return window['go']['controller']['FileSystemController']['GetDataDir']();
}

export function RevealInFolder(arg1) {
  return window['go']['controller']['FileSystemController']['RevealInFolder'](arg1);
}
