// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function GetImportEvidenceRetention():Promise<dto.ImportEvidenceRetentionDTO>;

export function GetImportRunDetail(arg1:number):Promise<dto.ImportRunDetailDTO>;

export function ListImportRuns(arg1:number):Promise<Array<dto.ImportRunSummaryDTO>>;

export function ListImportRunsPage(arg1:dto.ListImportRunsPageInput):Promise<dto.ImportRunPageDTO>;

export function PruneExpiredImportEvidence():Promise<Record<string, number>>;

export function SetImportEvidenceRetention(arg1:dto.SetImportEvidenceRetentionInput):Promise<dto.ImportEvidenceRetentionDTO>;
