// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImportEvidenceRetention() {
  return window['go']['controller']['ImportEvidenceController']['GetImportEvidenceRetention']();
}

export function GetImportRunDetail(arg1) {
  return window['go']['controller']['ImportEvidenceController']['GetImportRunDetail'](arg1);
}

export function ListImportRuns(arg1) {
  return window['go']['controller']['ImportEvidenceController']['ListImportRuns'](arg1);
}

export function ListImportRunsPage(arg1) {
  return window['go']['controller']['ImportEvidenceController']['ListImportRunsPage'](arg1);
}

export function PruneExpiredImportEvidence() {
  return window['go']['controller']['ImportEvidenceController']['PruneExpiredImportEvidence']();
}

export function SetImportEvidenceRetention(arg1) {
  return window['go']['controller']['ImportEvidenceController']['SetImportEvidenceRetention'](arg1);
}
