// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DismissMergeCandidate(arg1) {
  return window['go']['controller']['MergeGovernanceController']['DismissMergeCandidate'](arg1);
}

export function GetMergeCandidate(arg1) {
  return window['go']['controller']['MergeGovernanceController']['GetMergeCandidate'](arg1);
}

export function GetMergePolicy() {
  return window['go']['controller']['MergeGovernanceController']['GetMergePolicy']();
}

export function GetMergeScanRun(arg1) {
  return window['go']['controller']['MergeGovernanceController']['GetMergeScanRun'](arg1);
}

export function ListMergeCandidates(arg1) {
  return window['go']['controller']['MergeGovernanceController']['ListMergeCandidates'](arg1);
}

export function ScanMergeCandidates() {
  return window['go']['controller']['MergeGovernanceController']['ScanMergeCandidates']();
}

export function UpdateMergePolicy(arg1) {
  return window['go']['controller']['MergeGovernanceController']['UpdateMergePolicy'](arg1);
}
