// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function DismissMergeCandidate(arg1:dto.DismissMergeCandidateInput):Promise<void>;

export function GetMergeCandidate(arg1:number):Promise<dto.MergeCandidateDTO>;

export function GetMergePolicy():Promise<dto.MergePolicyDTO>;

export function GetMergeScanRun(arg1:number):Promise<dto.MergeScanRunDTO>;

export function ListMergeCandidates(arg1:string):Promise<Array<dto.MergeCandidateDTO>>;

export function ScanMergeCandidates():Promise<dto.MergeScanRunDTO>;

export function UpdateMergePolicy(arg1:dto.UpdateMergePolicyInput):Promise<dto.MergePolicyDTO>;
