// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function ExecuteCustomerMerge(arg1:dto.ExecuteCustomerMergeInput):Promise<dto.ExecuteCustomerMergeResult>;

export function GetCustomerMergeHistory(arg1:number):Promise<dto.CustomerMergeHistoryDetail>;

export function ListCustomerMergeHistory(arg1:dto.CustomerMergeHistoryQuery):Promise<dto.CustomerMergeHistoryPage>;

export function MergeProfiles(arg1:dto.MergeProfilesInput):Promise<dto.MergeProfilesResult>;

export function PreviewCustomerMerge(arg1:dto.CustomerMergePreviewInput):Promise<dto.CustomerMergePreviewResult>;

export function PreviewMergeProfiles(arg1:number,arg2:number):Promise<dto.MergeProfilesPreviewResult>;
