// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProductMaster(arg1) {
  return window['go']['controller']['ProductController']['CreateProductMaster'](arg1);
}

export function ImportProductCatalog(arg1) {
  return window['go']['controller']['ProductController']['ImportProductCatalog'](arg1);
}

export function ListProductMasters() {
  return window['go']['controller']['ProductController']['ListProductMasters']();
}

export function ListProductsByWave(arg1) {
  return window['go']['controller']['ProductController']['ListProductsByWave'](arg1);
}

export function SnapshotProductsForWave(arg1) {
  return window['go']['controller']['ProductController']['SnapshotProductsForWave'](arg1);
}

export function SnapshotProductsForWaveDetailed(arg1) {
  return window['go']['controller']['ProductController']['SnapshotProductsForWaveDetailed'](arg1);
}

export function UpdateProductMaster(arg1) {
  return window['go']['controller']['ProductController']['UpdateProductMaster'](arg1);
}
