// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateShipment(arg1) {
  return window['go']['controller']['ShipmentController']['CreateShipment'](arg1);
}

export function GetSupplierOrderLineShippedSummary(arg1) {
  return window['go']['controller']['ShipmentController']['GetSupplierOrderLineShippedSummary'](arg1);
}

export function ImportShipments(arg1) {
  return window['go']['controller']['ShipmentController']['ImportShipments'](arg1);
}

export function ListShipmentsByWave(arg1) {
  return window['go']['controller']['ShipmentController']['ListShipmentsByWave'](arg1);
}

export function MapAndReconcileShipments(arg1) {
  return window['go']['controller']['ShipmentController']['MapAndReconcileShipments'](arg1);
}

export function UpdateShipment(arg1) {
  return window['go']['controller']['ShipmentController']['UpdateShipment'](arg1);
}

export function VoidShipment(arg1) {
  return window['go']['controller']['ShipmentController']['VoidShipment'](arg1);
}
