// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignDemandToWave(arg1, arg2) {
  return window['go']['controller']['WaveController']['AssignDemandToWave'](arg1, arg2);
}

export function BatchAssignDemandToWave(arg1) {
  return window['go']['controller']['WaveController']['BatchAssignDemandToWave'](arg1);
}

export function BatchUnassignDemandFromWave(arg1) {
  return window['go']['controller']['WaveController']['BatchUnassignDemandFromWave'](arg1);
}

export function CloseWave(arg1) {
  return window['go']['controller']['WaveController']['CloseWave'](arg1);
}

export function CreateWave(arg1) {
  return window['go']['controller']['WaveController']['CreateWave'](arg1);
}

export function GenerateParticipants(arg1) {
  return window['go']['controller']['WaveController']['GenerateParticipants'](arg1);
}

export function GetHistoryGraph(arg1) {
  return window['go']['controller']['WaveController']['GetHistoryGraph'](arg1);
}

export function GetWave(arg1) {
  return window['go']['controller']['WaveController']['GetWave'](arg1);
}

export function GetWaveOverview(arg1) {
  return window['go']['controller']['WaveController']['GetWaveOverview'](arg1);
}

export function GetWaveWorkspaceSnapshot(arg1) {
  return window['go']['controller']['WaveController']['GetWaveWorkspaceSnapshot'](arg1);
}

export function ListAssignedDemandsByWave(arg1) {
  return window['go']['controller']['WaveController']['ListAssignedDemandsByWave'](arg1);
}

export function ListRecentHistory(arg1, arg2) {
  return window['go']['controller']['WaveController']['ListRecentHistory'](arg1, arg2);
}

export function ListWaveDashboardRows() {
  return window['go']['controller']['WaveController']['ListWaveDashboardRows']();
}

export function ListWaveFulfillmentRows(arg1) {
  return window['go']['controller']['WaveController']['ListWaveFulfillmentRows'](arg1);
}

export function ListWaveFulfillmentRowsFiltered(arg1) {
  return window['go']['controller']['WaveController']['ListWaveFulfillmentRowsFiltered'](arg1);
}

export function ListWaveParticipantRows(arg1) {
  return window['go']['controller']['WaveController']['ListWaveParticipantRows'](arg1);
}

export function ListWaves() {
  return window['go']['controller']['WaveController']['ListWaves']();
}

export function ListWavesFiltered(arg1) {
  return window['go']['controller']['WaveController']['ListWavesFiltered'](arg1);
}

export function ListWavesPaginated(arg1) {
  return window['go']['controller']['WaveController']['ListWavesPaginated'](arg1);
}

export function MapDemandLines(arg1) {
  return window['go']['controller']['WaveController']['MapDemandLines'](arg1);
}

export function RedoWaveAction(arg1) {
  return window['go']['controller']['WaveController']['RedoWaveAction'](arg1);
}

export function RunHistoryGC(arg1) {
  return window['go']['controller']['WaveController']['RunHistoryGC'](arg1);
}

export function UnassignDemandFromWave(arg1) {
  return window['go']['controller']['WaveController']['UnassignDemandFromWave'](arg1);
}

export function UndoWaveAction(arg1) {
  return window['go']['controller']['WaveController']['UndoWaveAction'](arg1);
}

export function UpdateWave(arg1) {
  return window['go']['controller']['WaveController']['UpdateWave'](arg1);
}

export function ValidateStepAccess(arg1, arg2) {
  return window['go']['controller']['WaveController']['ValidateStepAccess'](arg1, arg2);
}
