// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddException(arg1) {
  return window['go']['controller']['WorkspaceController']['AddException'](arg1);
}

export function ApplyRevision(arg1) {
  return window['go']['controller']['WorkspaceController']['ApplyRevision'](arg1);
}

export function AssignLines(arg1, arg2) {
  return window['go']['controller']['WorkspaceController']['AssignLines'](arg1, arg2);
}

export function AttachIdentity(arg1, arg2) {
  return window['go']['controller']['WorkspaceController']['AttachIdentity'](arg1, arg2);
}

export function CloseWave(arg1, arg2, arg3) {
  return window['go']['controller']['WorkspaceController']['CloseWave'](arg1, arg2, arg3);
}

export function CreateAddress(arg1) {
  return window['go']['controller']['WorkspaceController']['CreateAddress'](arg1);
}

export function CreateAlias(arg1) {
  return window['go']['controller']['WorkspaceController']['CreateAlias'](arg1);
}

export function CreateBundleComponent(arg1) {
  return window['go']['controller']['WorkspaceController']['CreateBundleComponent'](arg1);
}

export function CreateCarrierMapping(arg1) {
  return window['go']['controller']['WorkspaceController']['CreateCarrierMapping'](arg1);
}

export function CreateCustomer(arg1, arg2) {
  return window['go']['controller']['WorkspaceController']['CreateCustomer'](arg1, arg2);
}

export function CreateGrant(arg1, arg2, arg3, arg4) {
  return window['go']['controller']['WorkspaceController']['CreateGrant'](arg1, arg2, arg3, arg4);
}

export function CreatePlatform(arg1) {
  return window['go']['controller']['WorkspaceController']['CreatePlatform'](arg1);
}

export function CreateProduct(arg1) {
  return window['go']['controller']['WorkspaceController']['CreateProduct'](arg1);
}

export function CreateTemplate(arg1) {
  return window['go']['controller']['WorkspaceController']['CreateTemplate'](arg1);
}

export function CreateWave(arg1, arg2) {
  return window['go']['controller']['WorkspaceController']['CreateWave'](arg1, arg2);
}

export function DecideDuplicate(arg1, arg2) {
  return window['go']['controller']['WorkspaceController']['DecideDuplicate'](arg1, arg2);
}

export function DeleteCarrierMapping(arg1) {
  return window['go']['controller']['WorkspaceController']['DeleteCarrierMapping'](arg1);
}

export function DeleteException(arg1) {
  return window['go']['controller']['WorkspaceController']['DeleteException'](arg1);
}

export function DeleteQuantitySplitRule(arg1) {
  return window['go']['controller']['WorkspaceController']['DeleteQuantitySplitRule'](arg1);
}

export function DeleteRule(arg1) {
  return window['go']['controller']['WorkspaceController']['DeleteRule'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['controller']['WorkspaceController']['DeleteTemplate'](arg1);
}

export function DismissRevision(arg1) {
  return window['go']['controller']['WorkspaceController']['DismissRevision'](arg1);
}

export function DocumentTypeCatalog() {
  return window['go']['controller']['WorkspaceController']['DocumentTypeCatalog']();
}

export function EnsureBuiltinPlatforms() {
  return window['go']['controller']['WorkspaceController']['EnsureBuiltinPlatforms']();
}

export function EnsureBuiltinTemplates() {
  return window['go']['controller']['WorkspaceController']['EnsureBuiltinTemplates']();
}

export function ExportFactoryOrder(arg1) {
  return window['go']['controller']['WorkspaceController']['ExportFactoryOrder'](arg1);
}

export function ExportFactoryOrderFile(arg1) {
  return window['go']['controller']['WorkspaceController']['ExportFactoryOrderFile'](arg1);
}

export function ExportWritebackFile(arg1) {
  return window['go']['controller']['WorkspaceController']['ExportWritebackFile'](arg1);
}

export function GenerateFactoryOrder(arg1, arg2) {
  return window['go']['controller']['WorkspaceController']['GenerateFactoryOrder'](arg1, arg2);
}

export function GenerateFactoryOrderForResults(arg1, arg2, arg3) {
  return window['go']['controller']['WorkspaceController']['GenerateFactoryOrderForResults'](arg1, arg2, arg3);
}

export function GenerateWritebacks(arg1) {
  return window['go']['controller']['WorkspaceController']['GenerateWritebacks'](arg1);
}

export function GetCustomer(arg1) {
  return window['go']['controller']['WorkspaceController']['GetCustomer'](arg1);
}

export function GetSettings() {
  return window['go']['controller']['WorkspaceController']['GetSettings']();
}

export function GetTemplate(arg1) {
  return window['go']['controller']['WorkspaceController']['GetTemplate'](arg1);
}

export function GetWave(arg1) {
  return window['go']['controller']['WorkspaceController']['GetWave'](arg1);
}

export function Home() {
  return window['go']['controller']['WorkspaceController']['Home']();
}

export function ImportCarrierMappings(arg1, arg2, arg3, arg4) {
  return window['go']['controller']['WorkspaceController']['ImportCarrierMappings'](arg1, arg2, arg3, arg4);
}

export function ImportFile(arg1, arg2, arg3) {
  return window['go']['controller']['WorkspaceController']['ImportFile'](arg1, arg2, arg3);
}

export function ImportShipment(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['controller']['WorkspaceController']['ImportShipment'](arg1, arg2, arg3, arg4, arg5);
}

export function ImportShipmentFile(arg1, arg2, arg3) {
  return window['go']['controller']['WorkspaceController']['ImportShipmentFile'](arg1, arg2, arg3);
}

export function IngestDocument(arg1, arg2) {
  return window['go']['controller']['WorkspaceController']['IngestDocument'](arg1, arg2);
}

export function InspectSampleFile(arg1, arg2, arg3) {
  return window['go']['controller']['WorkspaceController']['InspectSampleFile'](arg1, arg2, arg3);
}

export function ListAddresses(arg1) {
  return window['go']['controller']['WorkspaceController']['ListAddresses'](arg1);
}

export function ListAliases(arg1) {
  return window['go']['controller']['WorkspaceController']['ListAliases'](arg1);
}

export function ListCarrierMappings(arg1) {
  return window['go']['controller']['WorkspaceController']['ListCarrierMappings'](arg1);
}

export function ListCustomers() {
  return window['go']['controller']['WorkspaceController']['ListCustomers']();
}

export function ListEntitlementInstances(arg1) {
  return window['go']['controller']['WorkspaceController']['ListEntitlementInstances'](arg1);
}

export function ListExceptions(arg1) {
  return window['go']['controller']['WorkspaceController']['ListExceptions'](arg1);
}

export function ListInboxRows() {
  return window['go']['controller']['WorkspaceController']['ListInboxRows']();
}

export function ListPlatforms() {
  return window['go']['controller']['WorkspaceController']['ListPlatforms']();
}

export function ListProducts() {
  return window['go']['controller']['WorkspaceController']['ListProducts']();
}

export function ListQuantitySplitRules(arg1) {
  return window['go']['controller']['WorkspaceController']['ListQuantitySplitRules'](arg1);
}

export function ListResultViews(arg1) {
  return window['go']['controller']['WorkspaceController']['ListResultViews'](arg1);
}

export function ListRules(arg1) {
  return window['go']['controller']['WorkspaceController']['ListRules'](arg1);
}

export function ListSupplierOrderLines(arg1) {
  return window['go']['controller']['WorkspaceController']['ListSupplierOrderLines'](arg1);
}

export function ListSupplierOrders(arg1) {
  return window['go']['controller']['WorkspaceController']['ListSupplierOrders'](arg1);
}

export function ListTemplates() {
  return window['go']['controller']['WorkspaceController']['ListTemplates']();
}

export function ListWaves() {
  return window['go']['controller']['WorkspaceController']['ListWaves']();
}

export function ListWritebacksByWave(arg1) {
  return window['go']['controller']['WorkspaceController']['ListWritebacksByWave'](arg1);
}

export function MarkWritebackFailed(arg1, arg2) {
  return window['go']['controller']['WorkspaceController']['MarkWritebackFailed'](arg1, arg2);
}

export function MarkWritebackSent(arg1) {
  return window['go']['controller']['WorkspaceController']['MarkWritebackSent'](arg1);
}

export function MoveLines(arg1, arg2) {
  return window['go']['controller']['WorkspaceController']['MoveLines'](arg1, arg2);
}

export function NamedTransformers() {
  return window['go']['controller']['WorkspaceController']['NamedTransformers']();
}

export function PreviewMapping(arg1, arg2, arg3, arg4) {
  return window['go']['controller']['WorkspaceController']['PreviewMapping'](arg1, arg2, arg3, arg4);
}

export function PreviewTemplate(arg1, arg2, arg3) {
  return window['go']['controller']['WorkspaceController']['PreviewTemplate'](arg1, arg2, arg3);
}

export function ProductTotals(arg1) {
  return window['go']['controller']['WorkspaceController']['ProductTotals'](arg1);
}

export function ReopenWave(arg1) {
  return window['go']['controller']['WorkspaceController']['ReopenWave'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['controller']['WorkspaceController']['SaveSettings'](arg1);
}

export function SemanticDictionary() {
  return window['go']['controller']['WorkspaceController']['SemanticDictionary']();
}

export function SetResultAddress(arg1, arg2) {
  return window['go']['controller']['WorkspaceController']['SetResultAddress'](arg1, arg2);
}

export function UpdateAlias(arg1, arg2) {
  return window['go']['controller']['WorkspaceController']['UpdateAlias'](arg1, arg2);
}

export function UpdateCarrierMapping(arg1) {
  return window['go']['controller']['WorkspaceController']['UpdateCarrierMapping'](arg1);
}

export function UpdateCustomer(arg1) {
  return window['go']['controller']['WorkspaceController']['UpdateCustomer'](arg1);
}

export function UpdateTemplate(arg1) {
  return window['go']['controller']['WorkspaceController']['UpdateTemplate'](arg1);
}

export function UpsertQuantitySplitRule(arg1) {
  return window['go']['controller']['WorkspaceController']['UpsertQuantitySplitRule'](arg1);
}

export function UpsertRule(arg1) {
  return window['go']['controller']['WorkspaceController']['UpsertRule'](arg1);
}

export function VoidFactoryOrder(arg1) {
  return window['go']['controller']['WorkspaceController']['VoidFactoryOrder'](arg1);
}
