// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignLines(arg1: number, arg2: number[]): Promise<void>;

export function AttachIdentity(arg1: number, arg2: number): Promise<void>;

export function CloseWave(arg1: number, arg2: string, arg3: string): Promise<void>;

export function CreateAddress(arg1: Record<string, unknown>): Promise<Record<string, unknown>>;

export function CreateAlias(arg1: Record<string, unknown>): Promise<Record<string, unknown>>;

export function CreateCarrierMapping(arg1: Record<string, unknown>): Promise<Record<string, unknown>>;

export function CreateCustomer(arg1: string, arg2: string): Promise<Record<string, unknown>>;

export function CreateGrant(arg1: number, arg2: number, arg3: number, arg4: number): Promise<Record<string, unknown>>;

export function CreateProduct(arg1: Record<string, unknown>): Promise<Record<string, unknown>>;

export function CreateTemplate(arg1: Record<string, unknown>): Promise<Record<string, unknown>>;

export function CreateWave(arg1: string, arg2: string): Promise<Record<string, unknown>>;

export function EnsureBuiltinPlatforms(): Promise<void>;

export function ExportFactoryOrder(arg1: number): Promise<Record<string, unknown>>;

export function GenerateFactoryOrder(arg1: number, arg2: number): Promise<Record<string, unknown>>;

export function GenerateWritebacks(arg1: number): Promise<Record<string, unknown>[]>;

export function GetCustomer(arg1: number): Promise<Record<string, unknown>>;

export function GetSettings(): Promise<Record<string, unknown>>;

export function GetWave(arg1: number): Promise<Record<string, unknown>>;

export function Home(): Promise<Record<string, unknown>>;

export function ImportShipment(arg1: string, arg2: string, arg3: string, arg4: string, arg5: number): Promise<Record<string, unknown>>;

export function IngestDocument(arg1: Record<string, unknown>, arg2: Record<string, unknown>[]): Promise<Record<string, unknown>>;

export function ListAddresses(arg1: number): Promise<Record<string, unknown>[]>;

export function ListAliases(arg1: number): Promise<Record<string, unknown>[]>;

export function ListCarrierMappings(arg1: number): Promise<Record<string, unknown>[]>;

export function ListCustomers(): Promise<Record<string, unknown>[]>;

export function ListInboxRows(): Promise<Record<string, unknown>[]>;

export function ListPlatforms(): Promise<Record<string, unknown>[]>;

export function ListProducts(): Promise<Record<string, unknown>[]>;

export function ListResultViews(arg1: number): Promise<Record<string, unknown>[]>;

export function ListRules(arg1: number): Promise<Record<string, unknown>[]>;

export function ListSupplierOrderLines(arg1: number): Promise<Record<string, unknown>[]>;

export function ListSupplierOrders(arg1: number): Promise<Record<string, unknown>[]>;

export function ListTemplates(): Promise<Record<string, unknown>[]>;

export function ListWaves(): Promise<Record<string, unknown>[]>;

export function NamedTransformers(): Promise<string[]>;

export function ProductTotals(arg1: number): Promise<Record<string, unknown>[]>;

export function ReopenWave(arg1: number): Promise<void>;

export function SaveSettings(arg1: Record<string, unknown>): Promise<void>;

export function SemanticDictionary(): Promise<string[]>;

export function SetResultAddress(arg1: number, arg2: number): Promise<void>;

export function UpsertRule(arg1: Record<string, unknown>): Promise<Record<string, unknown>>;

export function VoidFactoryOrder(arg1: number): Promise<void>;
