// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {app} from '../models';
import {alignment} from '../models';

export function AssignLines(arg1:number,arg2:Array<number>):Promise<void>;

export function AttachIdentity(arg1:number,arg2:number):Promise<void>;

export function CloseWave(arg1:number,arg2:string,arg3:string):Promise<void>;

export function CreateAddress(arg1:domain.RecipientAddress):Promise<domain.RecipientAddress>;

export function CreateAlias(arg1:domain.ProductAlias):Promise<domain.ProductAlias>;

export function CreateCarrierMapping(arg1:domain.CarrierMapping):Promise<domain.CarrierMapping>;

export function CreateCustomer(arg1:string,arg2:string):Promise<domain.CustomerProfile>;

export function CreateGrant(arg1:number,arg2:number,arg3:number,arg4:number):Promise<domain.FulfillmentResult>;

export function CreateProduct(arg1:domain.ProductItem):Promise<domain.ProductItem>;

export function CreateTemplate(arg1:domain.TemplateConfig):Promise<domain.TemplateConfig>;

export function CreateWave(arg1:string,arg2:string):Promise<domain.Wave>;

export function EnsureBuiltinPlatforms():Promise<void>;

export function ExportFactoryOrder(arg1:number):Promise<domain.SupplierOrder>;

export function ExportFactoryOrderFile(arg1:number):Promise<app.ExportFileResult>;

export function GenerateFactoryOrder(arg1:number,arg2:number):Promise<app.GenerateFactoryOrderResult>;

export function GenerateWritebacks(arg1:number):Promise<Array<domain.ChannelWritebackItem>>;

export function GetCustomer(arg1:number):Promise<domain.CustomerProfile>;

export function GetSettings():Promise<domain.AppSettings>;

export function GetWave(arg1:number):Promise<domain.Wave>;

export function Home():Promise<app.HomeBuckets>;

export function ImportFile(arg1:number,arg2:number,arg3:string):Promise<app.ImportFileResult>;

export function ImportShipment(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<domain.Shipment>;

export function ImportShipmentFile(arg1:number,arg2:string):Promise<app.ImportShipmentFileResult>;

export function IngestDocument(arg1:domain.InputDocument,arg2:Array<app.IngestFactInput>):Promise<app.IngestDocumentResult>;

export function ListAddresses(arg1:number):Promise<Array<domain.RecipientAddress>>;

export function ListAliases(arg1:number):Promise<Array<domain.ProductAlias>>;

export function ListCarrierMappings(arg1:number):Promise<Array<domain.CarrierMapping>>;

export function ListCustomers():Promise<Array<domain.CustomerProfile>>;

export function ListInboxRows():Promise<Array<app.InboxRow>>;

export function ListPlatforms():Promise<Array<domain.Platform>>;

export function ListProducts():Promise<Array<domain.ProductItem>>;

export function ListResultViews(arg1:number):Promise<Array<app.ResultView>>;

export function ListRules(arg1:number):Promise<Array<domain.EntitlementRule>>;

export function ListSupplierOrderLines(arg1:number):Promise<Array<domain.SupplierOrderLine>>;

export function ListSupplierOrders(arg1:number):Promise<Array<domain.SupplierOrder>>;

export function ListTemplates():Promise<Array<domain.TemplateConfig>>;

export function ListWaves():Promise<Array<domain.Wave>>;

export function NamedTransformers():Promise<Array<string>>;

export function PreviewTemplate(arg1:number,arg2:string,arg3:number):Promise<alignment.TemplatePreview>;

export function ProductTotals(arg1:number):Promise<Array<app.ProductTotal>>;

export function ReopenWave(arg1:number):Promise<void>;

export function SaveSettings(arg1:domain.AppSettings):Promise<void>;

export function SemanticDictionary():Promise<Array<string>>;

export function SetResultAddress(arg1:number,arg2:number):Promise<void>;

export function UpdateAlias(arg1:number,arg2:number):Promise<void>;

export function UpsertRule(arg1:domain.EntitlementRule):Promise<domain.EntitlementRule>;

export function VoidFactoryOrder(arg1:number):Promise<void>;
