import { vi } from "vitest";

// Mock naive-ui composition APIs that require provider ancestors
vi.mock("naive-ui", async (importOriginal) => {
  const actual = await importOriginal<Record<string, unknown>>();
  return {
    ...actual,
    useMessage: () => ({
      success: vi.fn(),
      error: vi.fn(),
      warning: vi.fn(),
      info: vi.fn(),
      loading: vi.fn(),
    }),
    useDialog: () => ({
      success: vi.fn(),
      error: vi.fn(),
      warning: vi.fn(),
      info: vi.fn(),
      create: vi.fn(),
    }),
  };
});

vi.mock("@/shared/lib/wails/app.ts", () => ({
  isWailsRuntimeAvailable: vi.fn(() => false),
  assertWailsRuntime: vi.fn(),
  listDemandLines: vi.fn(async () => []),
  listDemandDocuments: vi.fn(async () => []),
  listDemandInboxRows: vi.fn(async () => []),
  listUnassignedDemandDocuments: vi.fn(async () => []),
  getDemandDocument: vi.fn(async () => ({})),
  importDemandDocument: vi.fn(async () => ({})),
  listWaves: vi.fn(async () => []),
  listWaveDashboardRows: vi.fn(async () => []),
  getWave: vi.fn(async () => ({ id: 1, name: "Test Wave" })),
  createWave: vi.fn(async () => ({ id: 1, name: "Test Wave" })),
  mapDemandLines: vi.fn(async () => ({
    createdLines: [],
    blockedLines: [],
  })),
  getWaveOverview: vi.fn(async () => ({
    wave: { id: 1, name: "Test Wave", lifecycleStage: "intake" },
    demandCount: 0,
    fulfillmentCount: 0,
    supplierOrderCount: 0,
    shipmentCount: 0,
    trackedFulfillmentCount: 0,
    acceptedReadyOrNotRequired: 0,
    acceptedWaitingForInput: 0,
    deferredCount: 0,
    excludedManualCount: 0,
    excludedDuplicateCount: 0,
    excludedRevokedCount: 0,
    mappingBlockedCount: 0,
    channelSyncJobCount: 0,
    channelSyncPendingCount: 0,
    channelSyncRunningCount: 0,
    channelSyncSuccessCount: 0,
    channelSyncPartialSuccessCount: 0,
    channelSyncFailedCount: 0,
    manualClosureDecisionCount: 0,
    manualUnsupportedCount: 0,
    manualSkippedCount: 0,
    manualCompletedCount: 0,
    projectedLifecycleStage: "intake",
    basisDriftSignals: [],
    hasDriftedBasis: false,
    hasRequiredReviewBasis: false,
  })),
  getWaveWorkspaceSnapshot: vi.fn(async () => ({
    wave: { id: 1, waveNo: "WAVE-1", name: "Test Wave", lifecycleStage: "intake" },
    projectedLifecycleStage: "intake",
    overview: {
      wave: { id: 1, name: "Test Wave", lifecycleStage: "intake" },
      demandCount: 0,
      fulfillmentCount: 0,
      supplierOrderCount: 0,
      shipmentCount: 0,
      trackedFulfillmentCount: 0,
      acceptedReadyOrNotRequired: 0,
      acceptedWaitingForInput: 0,
      deferredCount: 0,
      excludedManualCount: 0,
      excludedDuplicateCount: 0,
      excludedRevokedCount: 0,
      mappingBlockedCount: 0,
      channelSyncJobCount: 0,
      channelSyncPendingCount: 0,
      channelSyncRunningCount: 0,
      channelSyncSuccessCount: 0,
      channelSyncPartialSuccessCount: 0,
      channelSyncFailedCount: 0,
      manualClosureDecisionCount: 0,
      manualUnsupportedCount: 0,
      manualSkippedCount: 0,
      manualCompletedCount: 0,
      projectedLifecycleStage: "intake",
      basisDriftSignals: [],
      hasDriftedBasis: false,
      hasRequiredReviewBasis: false,
    },
    stepStates: [],
    guidance: [],
    basisSummary: {
      driftedCount: 0,
      requiredReviewCount: 0,
      hasDriftedBasis: false,
      hasRequiredReview: false,
    },
    historyHeadNodeId: 0,
    historyHeadProjectionHash: "",
    recentHistory: [],
  })),
  listWaveFulfillmentRows: vi.fn(async () => []),
  listWaveParticipantRows: vi.fn(async () => []),
  listRecentHistory: vi.fn(async () => []),
  assignDemandToWave: vi.fn(async () => {}),
  undoWaveAction: vi.fn(async () => ""),
  redoWaveAction: vi.fn(async () => ""),
  exportSupplierOrder: vi.fn(async () => ({})),
  listSupplierOrders: vi.fn(async () => []),
  getSupplierOrderByWave: vi.fn(async () => ({})),
  listLinesBySupplierOrder: vi.fn(async () => []),
  createShipment: vi.fn(async () => ({})),
  listShipmentsByWave: vi.fn(async () => []),
  createChannelSyncJob: vi.fn(async () => ({})),
  listChannelSyncJobsByWave: vi.fn(async () => []),
  planChannelClosure: vi.fn(async () => ({})),
  executeChannelSyncJob: vi.fn(async () => ({})),
  recordChannelClosureDecision: vi.fn(async () => []),
  retryChannelSyncJob: vi.fn(async () => ({})),
  listIntegrationProfiles: vi.fn(async () => []),
  listProfiles: vi.fn(async () => []),
  getProfile: vi.fn(async () => ({})),
  createProfile: vi.fn(async () => ({})),
  updateProfile: vi.fn(async () => ({})),
  deleteProfile: vi.fn(async () => {}),
  seedDefaultProfiles: vi.fn(async () => []),
  createProductMaster: vi.fn(async () => ({})),
  listProductMasters: vi.fn(async () => []),
  updateProductMaster: vi.fn(async () => ({})),
  snapshotProductsForWave: vi.fn(async () => []),
  listProductsByWave: vi.fn(async () => []),
  listAllocationPolicyRules: vi.fn(async () => []),
  createAllocationPolicyRule: vi.fn(async () => ({})),
  updateAllocationPolicyRule: vi.fn(async () => ({})),
  deleteAllocationPolicyRule: vi.fn(async () => {}),
  reconcileWave: vi.fn(async () => ({ successes: [], failures: [] })),
  listAssignedDemandsByWave: vi.fn(async () => []),
  generateParticipants: vi.fn(async () => 0),
  listAdjustmentsByWave: vi.fn(async () => []),
  recordAdjustment: vi.fn(async () => ({})),
  pickCsvFile: vi.fn(async () => ""),
  pickZipFile: vi.fn(async () => ""),
  saveZoom: vi.fn(async () => {}),
}));
