// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AddressSnapshot {
    "source_address_id"?: number | null;
    "recipient_name": string;
    "phone": string;
    "country": string;
    "province": string;
    "city": string;
    "district": string;
    "address_line1": string;
    "address_line2": string;
    "postal_code": string;
}

export interface AppSettings {
    "ID": number;
    "Locale": string;
    "Theme": string;
    "Density": string;
    "DuplicateRecordMinutes": number;
    "DuplicateAskDays": number;
    "UpdatedAt": string;
}

export enum BlockReason {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    BlockUnalignedProduct = "unaligned_product",
    BlockUnusableAddress = "unusable_address",
    BlockIdentityUnattached = "identity_unattached",
    BlockQuantitySplitNotSumming = "quantity_split_not_summing",
};

/**
 * CarrierMapping translates a carrier as factory shipment files describe it
 * into the identifier a source (demand) platform accepts when tracking numbers
 * are written back. It is a loose description-to-ID lookup, not a precise
 * carrier registry:
 * 
 *   - PlatformID is the source platform whose writeback consumes ExternalCode.
 *   - InternalName is the carrier description as it appears in factory
 *     shipment files (e.g. 申通快递, 韵达); matching normalizes it (trim,
 *     case-fold, strip 快递/速运/物流/速递 suffixes) and tolerates
 *     containment either way.
 *   - ExternalCode is the carrier ID the source platform accepts, rendered as
 *     shipment.carrier_code in writeback layouts.
 *   - InternalCode is an optional internal key and may stay empty.
 */
export interface CarrierMapping {
    "ID": number;
    "PlatformID": number;
    "ExternalCode": string;
    "InternalCode": string;
    "InternalName": string;
    "CreatedAt": string;
    "UpdatedAt": string;
}

/**
 * ChannelWritebackItem is one parcel of one source fact's external writeback.
 * Quantity mirrors the shipment's parcel quantity; RetryCount and ErrorMessage
 * together form the retry history (the error text is the error of the latest
 * attempt, kept even after a later success).
 */
export interface ChannelWritebackItem {
    "ID": number;
    "InputFactID": number;
    "ShipmentID": number;
    "TrackingNo": string;
    "CarrierCode": string;
    "Quantity": number;
    "Status": string;
    "TemplateID": number;
    "TemplateVersion": number;
    "RetryCount": number;
    "ErrorMessage": string;
    "Payload": string;
    "CreatedAt": string;
    "UpdatedAt": string;
}

export interface CustomerProfile {
    "ID": number;
    "DisplayName": string;
    "Notes": string;
    "ExtraData": string;
    "CreatedAt": string;
    "UpdatedAt": string;
}

export interface DuplicateObservation {
    "ID": number;
    "DocumentID": number;
    "ExistingFactID": number;
    "Verdict": string;
    "Reason": string;
    "Decided": boolean;

    /**
     * ExtraData carries a JSON snapshot of the original ingest input so a
     * later operator decision can replay the fact creation.
     */
    "ExtraData": string;
    "CreatedAt": string;
    "UpdatedAt": string;
}

export interface EntitlementException {
    "ID": number;
    "WaveID": number;
    "ProductID": number;
    "InstanceID": number;
    "Quantity": number;
    "Note": string;
    "CreatedAt": string;
    "UpdatedAt": string;
}

export interface EntitlementRule {
    "ID": number;
    "WaveID": number;
    "ProductID": number;
    "Selector": EntitlementSelector;
    "Quantity": number;
    "Active": boolean;
    "ExtraData": string;
    "CreatedAt": string;
    "UpdatedAt": string;
}

export interface EntitlementSelector {
    "type": string;
    "platform_id"?: number;
    "level"?: string;
    "instance_id"?: number | null;
}

export interface FulfillmentResult {
    "ID": number;
    "WaveID": number;
    "SourceKind": string;
    "EntitlementInstanceID": number | null;
    "InputFactLineID": number | null;
    "InputFactID": number | null;
    "CustomerProfileID": number | null;
    "ProductItemID": number | null;
    "Quantity": number;
    "Address": AddressSnapshot;
    "Frozen": boolean;
    "AddressPinned": boolean;
    "ExtraData": string;
    "CreatedAt": string;
    "UpdatedAt": string;
}

export interface InputDocument {
    "ID": number;
    "PlatformID": number;
    "DocumentType": string;
    "Direction": string;
    "OriginalName": string;
    "RawPayload": string;
    "TemplateID": number | null;
    "TemplateVersion": number;
    "ImportedAt": string;
    "ExtraData": string;
    "CreatedAt": string;
    "UpdatedAt": string;
}

export interface InputFact {
    "ID": number;
    "DocumentID": number | null;
    "PlatformID": number;
    "Kind": string;
    "StableExternalID": string;
    "CustomerProfileID": number | null;
    "PlatformIdentityID": number | null;
    "MembershipLevel": string;
    "SourceDocumentNo": string;
    "SourceCreatedAt": string | null;

    /**
     * RevisesID points at the fact this input revises; the revision starts
     * pending (RevisionAppliedAt nil) and only enters waves once applied.
     */
    "RevisesID": number | null;
    "RevisionAppliedAt": string | null;
    "ExtraData": string;
    "CreatedAt": string;
    "UpdatedAt": string;
}

export interface InputFactLine {
    "ID": number;
    "FactID": number;
    "SourceLineNo": number;
    "ExternalSKU": string;
    "ExternalTitle": string;
    "ExternalSpec": string;
    "ProductItemID": number | null;
    "Quantity": number;
    "WaveID": number | null;
    "ExtraData": string;
    "CreatedAt": string;
    "UpdatedAt": string;
}

export interface Platform {
    "ID": number;
    "Key": string;
    "Name": string;
    "Kind": string;
    "Notes": string;
    "ExtraData": string;
    "CreatedAt": string;
    "UpdatedAt": string;
}

export interface ProductAlias {
    "ID": number;
    "ProductItemID": number;
    "PlatformID": number;
    "ExternalProductID": string;
    "Title": string;
    "Spec": string;
    "ExtraData": string;
    "CreatedAt": string;
    "UpdatedAt": string;
}

export interface ProductBundleComponent {
    "ID": number;
    "AliasID": number;
    "ProductItemID": number;
    "Quantity": number;
    "CreatedAt": string;
    "UpdatedAt": string;
}

export interface ProductItem {
    "ID": number;
    "Name": string;
    "FactoryPlatformID": number;
    "FactorySKU": string;
    "Notes": string;
    "ExtraData": string;
    "CreatedAt": string;
    "UpdatedAt": string;
}

export interface QuantitySplitComponent {
    "ID": number;
    "RuleID": number;
    "ProductItemID": number;
    "Quantity": number;
    "CreatedAt": string;
    "UpdatedAt": string;
}

/**
 * QuantitySplitRule is the advanced exception that spreads one input fact
 * line's quantity over several unified product facts for one wave and one
 * source line (platform + external key). Components carry the absolute
 * quantity apportioned to each product; they must sum to the line quantity.
 */
export interface QuantitySplitRule {
    "ID": number;
    "WaveID": number;
    "PlatformID": number;
    "ExternalKey": string;
    "Components": QuantitySplitComponent[] | null;
    "CreatedAt": string;
    "UpdatedAt": string;
}

export interface RecipientAddress {
    "ID": number;
    "CustomerProfileID": number;
    "Label": string;
    "RecipientName": string;
    "Phone": string;
    "Country": string;
    "Province": string;
    "City": string;
    "District": string;
    "AddressLine1": string;
    "AddressLine2": string;
    "PostalCode": string;
    "IsDefault": boolean;
    "ExtraData": string;
    "CreatedAt": string;
    "UpdatedAt": string;
}

export interface Shipment {
    "ID": number;
    "TrackingID": string;
    "CarrierCode": string;
    "CarrierName": string;
    "TrackingNo": string;
    "ShippedAt": string | null;
    "Quantity": number;
    "ExtraData": string;
    "CreatedAt": string;
    "UpdatedAt": string;
}

export interface SupplierOrder {
    "ID": number;
    "WaveID": number;
    "FactoryPlatformID": number;
    "Status": string;
    "TemplateID": number;
    "TemplateVersion": number;
    "ExportedAt": string | null;
    "VoidedAt": string | null;
    "ExportPayload": string;
    "ExtraData": string;
    "CreatedAt": string;
    "UpdatedAt": string;
}

export interface SupplierOrderLine {
    "ID": number;
    "SupplierOrderID": number;
    "ProductItemID": number;
    "FactorySKU": string;
    "Quantity": number;
    "TrackingID": string;
    "TrackingRetired": boolean;
    "ExtraData": string;
    "CreatedAt": string;
    "UpdatedAt": string;
}

export interface TemplateConfig {
    "ID": number;
    "PlatformID": number;
    "DocumentType": string;
    "Direction": string;
    "Name": string;
    "Version": number;
    "Builtin": boolean;
    "MappingJSON": string;
    "LayoutJSON": string;
    "Notes": string;
    "ExtraData": string;
    "CreatedAt": string;
    "UpdatedAt": string;
}

export interface Wave {
    "ID": number;
    "WaveNo": string;
    "Name": string;
    "Notes": string;
    "CloseResult": string;
    "CloseNote": string;
    "ClosedAt": string | null;
    "ReopenedAt": string | null;
    "ExtraData": string;
    "CreatedAt": string;
    "UpdatedAt": string;
}

export enum WorkState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    WorkStateBlocked = "blocked",
    WorkStateReady = "ready",
    WorkStateInFactory = "in_factory",
    WorkStateShipped = "shipped",
    WorkStateWritebackFailed = "writeback_failed",
};
