// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function BindAddressToLine(arg1:dto.BindAddressInput):Promise<dto.CustomerAddressDTO>;

export function CreateAddress(arg1:dto.CreateAddressInput):Promise<dto.CustomerAddressDTO>;

export function DeleteAddress(arg1:number):Promise<void>;

export function GetAddress(arg1:number):Promise<dto.CustomerAddressDTO>;

export function ListAddressesByProfile(arg1:number):Promise<Array<dto.CustomerAddressDTO>>;

export function UnbindAddressFromLine(arg1:number):Promise<void>;

export function UpdateAddress(arg1:dto.UpdateAddressInput):Promise<dto.CustomerAddressDTO>;
