// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function ListAdjustmentsByWave(arg1:number):Promise<Array<dto.FulfillmentAdjustmentDTO>>;

export function RecordAdjustment(arg1:dto.RecordAdjustmentInput):Promise<dto.FulfillmentAdjustmentDTO>;
