// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAllocationPolicyRule(arg1) {
  return window['go']['main']['AllocationPolicyController']['CreateAllocationPolicyRule'](arg1);
}

export function DeleteAllocationPolicyRule(arg1) {
  return window['go']['main']['AllocationPolicyController']['DeleteAllocationPolicyRule'](arg1);
}

export function ListAllocationPolicyRules(arg1) {
  return window['go']['main']['AllocationPolicyController']['ListAllocationPolicyRules'](arg1);
}

export function ReconcileWave(arg1) {
  return window['go']['main']['AllocationPolicyController']['ReconcileWave'](arg1);
}

export function UpdateAllocationPolicyRule(arg1) {
  return window['go']['main']['AllocationPolicyController']['UpdateAllocationPolicyRule'](arg1);
}
