// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CreateAllocationPolicyRule(arg1:dto.CreateAllocationPolicyRuleInput):Promise<dto.AllocationPolicyRuleDTO>;

export function DeleteAllocationPolicyRule(arg1:number):Promise<void>;

export function ListAllocationPolicyRules(arg1:number):Promise<Array<dto.AllocationPolicyRuleDTO>>;

export function ReconcileWave(arg1:number):Promise<dto.ReconcileResultDTO>;

export function UpdateAllocationPolicyRule(arg1:dto.UpdateAllocationPolicyRuleInput):Promise<dto.AllocationPolicyRuleDTO>;
