// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function PingDB() {
  return window['go']['main']['App']['PingDB']();
}

export function ValidateBatch(arg1) {
  return window['go']['main']['App']['ValidateBatch'](arg1);
}
