// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PickCSVFile() {
  return window['go']['main']['App']['PickCSVFile']();
}

export function PickZIPFile() {
  return window['go']['main']['App']['PickZIPFile']();
}
