// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function GetDashboard() {
  return window['go']['main']['App']['GetDashboard']();
}

export function ListDispatchRecords() {
  return window['go']['main']['App']['ListDispatchRecords']();
}

export function ListMembers() {
  return window['go']['main']['App']['ListMembers']();
}

export function ListProducts() {
  return window['go']['main']['App']['ListProducts']();
}

export function ListTemplates() {
  return window['go']['main']['App']['ListTemplates']();
}

export function PingDB() {
  return window['go']['main']['App']['PingDB']();
}

export function ValidateBatch(arg1) {
  return window['go']['main']['App']['ValidateBatch'](arg1);
}
