// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {model} from '../models';

export function AllocateByTags(arg1:number):Promise<number>;

export function AssignProductTag(arg1:number,arg2:string,arg3:string):Promise<void>;

export function BackupDatabase():Promise<string>;

export function BindDefaultAddresses(arg1:number):Promise<Record<string, number>>;

export function Bootstrap():Promise<main.BootstrapPayload>;

export function CreateTemplate(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.TemplateItem>;

export function CreateWave(arg1:string):Promise<model.Wave>;

export function DeleteWave(arg1:number):Promise<void>;

export function ExportOrderCSV(arg1:number,arg2:number):Promise<string>;

export function GetDashboard():Promise<main.DashboardPayload>;

export function GetProductImages(arg1:number):Promise<Array<model.ProductImage>>;

export function ImportDispatchWave(arg1:number,arg2:string,arg3:number):Promise<void>;

export function ImportToWave(arg1:number,arg2:string,arg3:number):Promise<void>;

export function ListDispatchRecords(arg1:number):Promise<Array<main.DispatchRecordItem>>;

export function ListMembers(arg1:number,arg2:number,arg3:string,arg4:string):Promise<main.MemberListPayload>;

export function ListProductTags(arg1:string):Promise<Array<string>>;

export function ListProducts(arg1:number,arg2:number,arg3:string,arg4:string):Promise<main.ProductListPayload>;

export function ListProductsWithTags(arg1:number,arg2:string,arg3:number,arg4:number):Promise<main.ProductListWithTagsPayload>;

export function ListTemplates():Promise<Array<main.TemplateItem>>;

export function ListWaves(arg1:string):Promise<Array<main.WaveItem>>;

export function ListDefaultTemplates():Promise<Array<main.TemplateItem>>;

export function PickCSVFile():Promise<string>;

export function PickZIPFile():Promise<string>;

export function PingDB():Promise<string>;

export function PreviewExport(arg1:number):Promise<Record<string, number>>;

export function RemoveProductTag(arg1:number,arg2:string,arg3:string):Promise<void>;

export function RestoreDatabase():Promise<void>;

export function SetDefaultAddress(arg1:number,arg2:number):Promise<void>;

export function UpdateProduct(arg1:model.Product):Promise<void>;
