// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CreateCarrierMapping(arg1:dto.CreateCarrierMappingInput):Promise<dto.CarrierMappingDTO>;

export function CreateChannelSyncJob(arg1:dto.CreateChannelSyncJobInput):Promise<dto.ChannelSyncJobDTO>;

export function DeleteCarrierMapping(arg1:number):Promise<void>;

export function ExecuteChannelSyncJob(arg1:number):Promise<dto.ExecuteSyncResult>;

export function ListCarrierMappings(arg1:number):Promise<Array<dto.CarrierMappingDTO>>;

export function ListChannelSyncJobsByWave(arg1:number):Promise<Array<dto.ChannelSyncJobDTO>>;

export function ListConnectorCapabilities():Promise<Record<string, any>>;

export function ListIntegrationProfiles():Promise<Array<dto.IntegrationProfileSummaryDTO>>;

export function PlanChannelClosure(arg1:dto.PlanChannelClosureInput):Promise<dto.PlanChannelClosureResult>;

export function RecordChannelClosureDecision(arg1:dto.RecordClosureDecisionInput):Promise<Array<dto.ClosureDecisionRecordDTO>>;

export function RetryChannelSyncJob(arg1:number):Promise<dto.ExecuteSyncResult>;
