// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CreateChannelSyncJob(arg1:dto.CreateChannelSyncJobInput):Promise<dto.ChannelSyncJobDTO>;

export function PlanChannelClosure(arg1:dto.PlanChannelClosureInput):Promise<dto.PlanChannelClosureResult>;

export function ListChannelSyncJobsByWave(arg1:number):Promise<Array<dto.ChannelSyncJobDTO>>;
