// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateChannelSyncJob(arg1) {
  return window['go']['main']['ChannelSyncController']['CreateChannelSyncJob'](arg1);
}

export function PlanChannelClosure(arg1) {
  return window['go']['main']['ChannelSyncController']['PlanChannelClosure'](arg1);
}

export function ListChannelSyncJobsByWave(arg1) {
  return window['go']['main']['ChannelSyncController']['ListChannelSyncJobsByWave'](arg1);
}
