// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCustomerResolutionFeaturePolicy() {
  return window['go']['main']['CustomerResolutionFeaturePolicyController']['GetCustomerResolutionFeaturePolicy']();
}

export function UpdateCustomerResolutionFeaturePolicy(arg1) {
  return window['go']['main']['CustomerResolutionFeaturePolicyController']['UpdateCustomerResolutionFeaturePolicy'](arg1);
}
