// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomerIdentity(arg1) {
  return window['go']['main']['CustomerProfileController']['AddCustomerIdentity'](arg1);
}

export function CreateCustomerProfile(arg1) {
  return window['go']['main']['CustomerProfileController']['CreateCustomerProfile'](arg1);
}

export function DeleteCustomerIdentity(arg1) {
  return window['go']['main']['CustomerProfileController']['DeleteCustomerIdentity'](arg1);
}

export function DeleteCustomerProfile(arg1) {
  return window['go']['main']['CustomerProfileController']['DeleteCustomerProfile'](arg1);
}

export function DismissMergeSuggestion(arg1) {
  return window['go']['main']['CustomerProfileController']['DismissMergeSuggestion'](arg1);
}

export function GetCustomerProfile(arg1) {
  return window['go']['main']['CustomerProfileController']['GetCustomerProfile'](arg1);
}

export function GetMergeSuggestions() {
  return window['go']['main']['CustomerProfileController']['GetMergeSuggestions']();
}

export function GetSettings() {
  return window['go']['main']['CustomerProfileController']['GetSettings']();
}

export function ListCustomerProfiles(arg1, arg2, arg3) {
  return window['go']['main']['CustomerProfileController']['ListCustomerProfiles'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['main']['CustomerProfileController']['SaveSettings'](arg1);
}

export function UpdateCustomerProfile(arg1) {
  return window['go']['main']['CustomerProfileController']['UpdateCustomerProfile'](arg1);
}
