// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchUpdateDemandLineRouting(arg1) {
  return window['go']['main']['DemandController']['BatchUpdateDemandLineRouting'](arg1);
}

export function GetDemandDocument(arg1) {
  return window['go']['main']['DemandController']['GetDemandDocument'](arg1);
}

export function GetWaveRoutingStats(arg1) {
  return window['go']['main']['DemandController']['GetWaveRoutingStats'](arg1);
}

export function ImportDemandDocument(arg1) {
  return window['go']['main']['DemandController']['ImportDemandDocument'](arg1);
}

export function ListDemandDocuments() {
  return window['go']['main']['DemandController']['ListDemandDocuments']();
}

export function ListDemandInboxRows(arg1) {
  return window['go']['main']['DemandController']['ListDemandInboxRows'](arg1);
}

export function ListDemandLines(arg1) {
  return window['go']['main']['DemandController']['ListDemandLines'](arg1);
}

export function ListUnassignedDemandDocuments() {
  return window['go']['main']['DemandController']['ListUnassignedDemandDocuments']();
}

export function UpdateDemandLineRouting(arg1) {
  return window['go']['main']['DemandController']['UpdateDemandLineRouting'](arg1);
}
