// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function GetDemandDocument(arg1:number):Promise<dto.DemandDocumentDTO>;

export function ImportDemandDocument(arg1:dto.CreateDemandInput):Promise<dto.DemandDocumentDTO>;

export function ListDemandDocuments():Promise<Array<dto.DemandDocumentDTO>>;
