// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function GetDemandDocument(arg1:number):Promise<dto.DemandDocumentDTO>;

export function ImportDemandDocument(arg1:dto.CreateDemandInput):Promise<dto.DemandDocumentDTO>;

export function ListDemandDocuments():Promise<Array<dto.DemandDocumentDTO>>;

export function ListDemandInboxRows(arg1:dto.DemandInboxFilterInput):Promise<Array<dto.DemandInboxRowDTO>>;

export function ListDemandLines(arg1:number):Promise<Array<dto.DemandLineDTO>>;

export function ListUnassignedDemandDocuments():Promise<Array<dto.DemandDocumentDTO>>;
