// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDemandDocument(arg1) {
  return window['go']['main']['DemandController']['GetDemandDocument'](arg1);
}

export function ImportDemandDocument(arg1) {
  return window['go']['main']['DemandController']['ImportDemandDocument'](arg1);
}

export function ListDemandDocuments() {
  return window['go']['main']['DemandController']['ListDemandDocuments']();
}

export function ListDemandLines(arg1) {
  return window['go']['main']['DemandController']['ListDemandLines'](arg1);
}

export function ListUnassignedDemandDocuments() {
  return window['go']['main']['DemandController']['ListUnassignedDemandDocuments']();
}
