// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportSupplierOrder(arg1) {
  return window['go']['main']['ExportController']['ExportSupplierOrder'](arg1);
}

export function GetSupplierOrderByWave(arg1) {
  return window['go']['main']['ExportController']['GetSupplierOrderByWave'](arg1);
}

export function ListLinesBySupplierOrder(arg1) {
  return window['go']['main']['ExportController']['ListLinesBySupplierOrder'](arg1);
}

export function ListSupplierOrders() {
  return window['go']['main']['ExportController']['ListSupplierOrders']();
}
