// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function ExportSupplierOrder(arg1:number):Promise<Array<dto.SupplierOrderDTO>>;

export function ExportSupplierOrderForProfile(arg1:number,arg2:number):Promise<Array<dto.SupplierOrderDTO>>;

export function GenerateSupplierOrderFile(arg1:number):Promise<dto.SupplierOrderFileResultDTO>;

export function GetSupplierOrderByWave(arg1:number):Promise<Array<dto.SupplierOrderDTO>>;

export function ListLinesBySupplierOrder(arg1:number):Promise<Array<dto.SupplierOrderLineDTO>>;

export function ListSupplierOrders():Promise<Array<dto.SupplierOrderDTO>>;

export function MarkSupplierOrderSubmitted(arg1:dto.MarkSupplierOrderSubmittedInput):Promise<dto.SupplierOrderDTO>;

export function RecordSupplierOrderAcceptance(arg1:dto.RecordSupplierOrderAcceptanceInput):Promise<dto.SupplierOrderDTO>;
