// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function ExportSupplierOrder(arg1:number):Promise<dto.SupplierOrderDTO>;

export function ListSupplierOrders():Promise<Array<dto.SupplierOrderDTO>>;
