// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDataDir():Promise<string>;

export function RevealInFolder(arg1:string):Promise<void>;
