// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function ListCustomerIdentityPlatforms():Promise<Array<string>>;

export function ListCustomerProfilesPage(arg1:dto.CustomerProfilePageFilterInput):Promise<dto.CustomerProfilePageResult>;

export function ListDemandInboxRowsPage(arg1:dto.DemandInboxFilterInput):Promise<dto.DemandInboxPageResult>;

export function ListProductMastersPage(arg1:dto.ProductMasterPageFilterInput):Promise<dto.ProductMasterPageResult>;

export function ListShipmentsByWavePage(arg1:dto.ShipmentByWavePageFilterInput):Promise<dto.ShipmentPageResult>;
