// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListMembers(arg1, arg2, arg3, arg4) {
  return window['go']['main']['MemberController']['ListMembers'](arg1, arg2, arg3, arg4);
}

export function SetDefaultAddress(arg1, arg2) {
  return window['go']['main']['MemberController']['SetDefaultAddress'](arg1, arg2);
}
