// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';

export function AddMemberAddress(arg1:number,arg2:string,arg3:string,arg4:string):Promise<model.MemberAddress>;

export function DeleteMemberAddress(arg1:number):Promise<void>;

export function ListMembers(arg1:number,arg2:number,arg3:string,arg4:string):Promise<main.MemberListPayload>;

export function ListWaveMembers(arg1:number):Promise<Array<main.MemberItem>>;

export function SetDefaultAddress(arg1:number,arg2:number):Promise<void>;

export function UpdateMemberAddress(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;
