// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMemberAddress(arg1, arg2, arg3, arg4) {
  return window['go']['main']['MemberController']['AddMemberAddress'](arg1, arg2, arg3, arg4);
}

export function DeleteMemberAddress(arg1) {
  return window['go']['main']['MemberController']['DeleteMemberAddress'](arg1);
}

export function ListMembers(arg1, arg2, arg3, arg4) {
  return window['go']['main']['MemberController']['ListMembers'](arg1, arg2, arg3, arg4);
}

export function ListWaveMembers(arg1) {
  return window['go']['main']['MemberController']['ListWaveMembers'](arg1);
}

export function RemoveMemberFromWave(arg1, arg2) {
  return window['go']['main']['MemberController']['RemoveMemberFromWave'](arg1, arg2);
}

export function SetDefaultAddress(arg1, arg2) {
  return window['go']['main']['MemberController']['SetDefaultAddress'](arg1, arg2);
}

export function UpdateMemberAddress(arg1, arg2, arg3, arg4) {
  return window['go']['main']['MemberController']['UpdateMemberAddress'](arg1, arg2, arg3, arg4);
}
