// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function DryRunCustomerMergeUndo(arg1:dto.CustomerMergeUndoDryRunInput):Promise<dto.CustomerMergeUndoDryRunResult>;

export function ExecuteCustomerMergeUndo(arg1:dto.ExecuteCustomerMergeUndoInput):Promise<dto.ExecuteCustomerMergeUndoResult>;

export function UndoCustomerMerge(arg1:dto.UndoCustomerMergeInput):Promise<dto.UndoCustomerMergeResult>;
