// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCustomerMerge(arg1) {
  return window['go']['main']['MergeController']['ExecuteCustomerMerge'](arg1);
}

export function GetCustomerMergeHistory(arg1) {
  return window['go']['main']['MergeController']['GetCustomerMergeHistory'](arg1);
}

export function ListCustomerMergeHistory(arg1) {
  return window['go']['main']['MergeController']['ListCustomerMergeHistory'](arg1);
}

export function MergeProfiles(arg1) {
  return window['go']['main']['MergeController']['MergeProfiles'](arg1);
}

export function PreviewCustomerMerge(arg1) {
  return window['go']['main']['MergeController']['PreviewCustomerMerge'](arg1);
}

export function PreviewMergeProfiles(arg1, arg2) {
  return window['go']['main']['MergeController']['PreviewMergeProfiles'](arg1, arg2);
}
