// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DryRunCustomerMergeUndo(arg1) {
  return window['go']['main']['MergeUndoController']['DryRunCustomerMergeUndo'](arg1);
}

export function ExecuteCustomerMergeUndo(arg1) {
  return window['go']['main']['MergeUndoController']['ExecuteCustomerMergeUndo'](arg1);
}

export function UndoCustomerMerge(arg1) {
  return window['go']['main']['MergeUndoController']['UndoCustomerMerge'](arg1);
}
