// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MergeProfiles(arg1) {
  return window['go']['main']['MergeController']['MergeProfiles'](arg1);
}
