// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CreateProductMaster(arg1:dto.CreateProductMasterInput):Promise<dto.ProductMasterDTO>;

export function ListProductMasters():Promise<Array<dto.ProductMasterDTO>>;

export function ListProductsByWave(arg1:number):Promise<Array<dto.ProductDTO>>;

export function SnapshotProductsForWave(arg1:dto.SnapshotProductsInput):Promise<Array<dto.ProductDTO>>;

export function UpdateProductMaster(arg1:dto.UpdateProductMasterInput):Promise<dto.ProductMasterDTO>;
