// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignProductTag(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['ProductController']['AssignProductTag'](arg1, arg2, arg3, arg4, arg5);
}

export function GetProductImages(arg1) {
  return window['go']['main']['ProductController']['GetProductImages'](arg1);
}

export function GetProductMasterImages(arg1) {
  return window['go']['main']['ProductController']['GetProductMasterImages'](arg1);
}

export function ListProductMasters(arg1, arg2, arg3, arg4) {
  return window['go']['main']['ProductController']['ListProductMasters'](arg1, arg2, arg3, arg4);
}

export function ListProductTags(arg1) {
  return window['go']['main']['ProductController']['ListProductTags'](arg1);
}

export function ListProducts(arg1, arg2, arg3, arg4) {
  return window['go']['main']['ProductController']['ListProducts'](arg1, arg2, arg3, arg4);
}

export function ListProductsWithTags(arg1, arg2, arg3, arg4) {
  return window['go']['main']['ProductController']['ListProductsWithTags'](arg1, arg2, arg3, arg4);
}

export function RemoveLevelTag(arg1, arg2, arg3) {
  return window['go']['main']['ProductController']['RemoveLevelTag'](arg1, arg2, arg3);
}

export function RemoveProductTag(arg1, arg2, arg3, arg4) {
  return window['go']['main']['ProductController']['RemoveProductTag'](arg1, arg2, arg3, arg4);
}

export function RemoveUserTag(arg1, arg2) {
  return window['go']['main']['ProductController']['RemoveUserTag'](arg1, arg2);
}

export function UpdateProduct(arg1) {
  return window['go']['main']['ProductController']['UpdateProduct'](arg1);
}

export function UpsertLevelTag(arg1, arg2, arg3, arg4) {
  return window['go']['main']['ProductController']['UpsertLevelTag'](arg1, arg2, arg3, arg4);
}

export function UpsertUserTag(arg1, arg2, arg3) {
  return window['go']['main']['ProductController']['UpsertUserTag'](arg1, arg2, arg3);
}
