// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProductMaster(arg1) {
  return window['go']['main']['ProductController']['CreateProductMaster'](arg1);
}

export function ListProductMasters() {
  return window['go']['main']['ProductController']['ListProductMasters']();
}

export function ListProductsByWave(arg1) {
  return window['go']['main']['ProductController']['ListProductsByWave'](arg1);
}

export function SnapshotProductsForWave(arg1) {
  return window['go']['main']['ProductController']['SnapshotProductsForWave'](arg1);
}

export function UpdateProductMaster(arg1) {
  return window['go']['main']['ProductController']['UpdateProductMaster'](arg1);
}
