// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignProductTag(arg1, arg2, arg3) {
  return window['go']['main']['ProductController']['AssignProductTag'](arg1, arg2, arg3);
}

export function GetProductImages(arg1) {
  return window['go']['main']['ProductController']['GetProductImages'](arg1);
}

export function ListProductTags(arg1) {
  return window['go']['main']['ProductController']['ListProductTags'](arg1);
}

export function ListProducts(arg1, arg2, arg3, arg4) {
  return window['go']['main']['ProductController']['ListProducts'](arg1, arg2, arg3, arg4);
}

export function ListProductsWithTags(arg1, arg2, arg3, arg4) {
  return window['go']['main']['ProductController']['ListProductsWithTags'](arg1, arg2, arg3, arg4);
}

export function RemoveProductTag(arg1, arg2, arg3) {
  return window['go']['main']['ProductController']['RemoveProductTag'](arg1, arg2, arg3);
}

export function UpdateProduct(arg1) {
  return window['go']['main']['ProductController']['UpdateProduct'](arg1);
}
