// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CreateProfile(arg1:dto.CreateProfileInput):Promise<dto.IntegrationProfileDTO>;

export function DeleteProfile(arg1:number):Promise<void>;

export function GetProfile(arg1:number):Promise<dto.IntegrationProfileDTO>;

export function ListProfiles():Promise<Array<dto.IntegrationProfileDTO>>;

export function SeedDefaultProfiles():Promise<Array<dto.IntegrationProfileDTO>>;

export function UpdateProfile(arg1:dto.UpdateProfileInput):Promise<dto.IntegrationProfileDTO>;
