// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProfile(arg1) {
  return window['go']['main']['ProfileController']['CreateProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['ProfileController']['DeleteProfile'](arg1);
}

export function GetProfile(arg1) {
  return window['go']['main']['ProfileController']['GetProfile'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['ProfileController']['ListProfiles']();
}

export function SeedDefaultProfiles() {
  return window['go']['main']['ProfileController']['SeedDefaultProfiles']();
}

export function UpdateProfile(arg1) {
  return window['go']['main']['ProfileController']['UpdateProfile'](arg1);
}
