// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CreateShipment(arg1:dto.CreateShipmentInput):Promise<dto.ShipmentDTO>;

export function ListShipmentsByWave(arg1:number):Promise<Array<dto.ShipmentDTO>>;
