// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CreateShipment(arg1:dto.CreateShipmentInput):Promise<dto.ShipmentDTO>;

export function GetSupplierOrderLineShippedSummary(arg1:number):Promise<Array<dto.SupplierOrderLineShippedDTO>>;

export function ImportShipments(arg1:dto.ImportShipmentInput):Promise<dto.ImportShipmentResult>;

export function ListShipmentsByWave(arg1:number):Promise<Array<dto.ShipmentDTO>>;

export function UpdateShipment(arg1:dto.UpdateShipmentInput):Promise<dto.ShipmentDTO>;

export function VoidShipment(arg1:dto.VoidShipmentInput):Promise<dto.ShipmentDTO>;
