// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateShipment(arg1) {
  return window['go']['main']['ShipmentController']['CreateShipment'](arg1);
}

export function ListShipmentsByWave(arg1) {
  return window['go']['main']['ShipmentController']['ListShipmentsByWave'](arg1);
}
