// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCustomerSplit(arg1) {
  return window['go']['main']['SplitController']['ExecuteCustomerSplit'](arg1);
}

export function GetCustomerSplitHistory(arg1) {
  return window['go']['main']['SplitController']['GetCustomerSplitHistory'](arg1);
}

export function ListCustomerSplitHistory(arg1) {
  return window['go']['main']['SplitController']['ListCustomerSplitHistory'](arg1);
}

export function PreviewCustomerSplit(arg1) {
  return window['go']['main']['SplitController']['PreviewCustomerSplit'](arg1);
}
