// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function ExecuteCustomerSplit(arg1:dto.ExecuteCustomerSplitInput):Promise<dto.ExecuteCustomerSplitResult>;

export function GetCustomerSplitHistory(arg1:number):Promise<dto.CustomerSplitHistoryDetail>;

export function ListCustomerSplitHistory(arg1:dto.CustomerSplitHistoryQuery):Promise<dto.CustomerSplitHistoryPage>;

export function PreviewCustomerSplit(arg1:dto.CustomerSplitPreviewInput):Promise<dto.CustomerSplitPreviewResult>;
