// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupDatabase() {
  return window['go']['main']['SystemController']['BackupDatabase']();
}

export function Bootstrap() {
  return window['go']['main']['SystemController']['Bootstrap']();
}

export function CreateFakeAddresses() {
  return window['go']['main']['SystemController']['CreateFakeAddresses']();
}

export function DeleteFakeAddresses() {
  return window['go']['main']['SystemController']['DeleteFakeAddresses']();
}

export function GetDashboard() {
  return window['go']['main']['SystemController']['GetDashboard']();
}

export function PingDB() {
  return window['go']['main']['SystemController']['PingDB']();
}

export function RestoreDatabase() {
  return window['go']['main']['SystemController']['RestoreDatabase']();
}

export function SaveZoom(arg1) {
  return window['go']['main']['SystemController']['SaveZoom'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['SystemController']['SetContext'](arg1);
}
