// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function BackupDatabase():Promise<string>;

export function Bootstrap():Promise<main.BootstrapPayload>;

export function GetDashboard():Promise<main.DashboardPayload>;

export function PingDB():Promise<string>;

export function RestoreDatabase():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
