// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTemplate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['TemplateController']['CreateTemplate'](arg1, arg2, arg3, arg4);
}

export function ListDefaultTemplates() {
  return window['go']['main']['TemplateController']['ListDefaultTemplates']();
}

export function ListTemplates() {
  return window['go']['main']['TemplateController']['ListTemplates']();
}

export function UpdateTemplate(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['TemplateController']['UpdateTemplate'](arg1, arg2, arg3, arg4, arg5);
}
