// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {service} from '../models';

export function AddFromPreset(arg1:string,arg2:string):Promise<main.TemplateItem>;

export function CreateTemplate(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.TemplateItem>;

export function DeleteTemplate(arg1:number):Promise<void>;

export function GetPresetContent(arg1:string,arg2:string):Promise<service.PresetContent>;

export function ListBuiltinPresets():Promise<Array<service.PresetInfo>>;

export function ListTemplates():Promise<Array<main.TemplateItem>>;

export function ListUserPresets():Promise<Array<service.PresetInfo>>;

export function UpdateTemplate(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;
