// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateTemplate(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.TemplateItem>;

export function ListDefaultTemplates():Promise<Array<main.TemplateItem>>;

export function ListTemplates():Promise<Array<main.TemplateItem>>;
