// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BindTemplateToProfile(arg1) {
  return window['go']['main']['TemplateController']['BindTemplateToProfile'](arg1);
}

export function CreateDocumentTemplate(arg1) {
  return window['go']['main']['TemplateController']['CreateDocumentTemplate'](arg1);
}

export function GetDefaultTemplateForProfile(arg1, arg2) {
  return window['go']['main']['TemplateController']['GetDefaultTemplateForProfile'](arg1, arg2);
}

export function ListBindingsByProfile(arg1) {
  return window['go']['main']['TemplateController']['ListBindingsByProfile'](arg1);
}

export function ListDocumentTemplates() {
  return window['go']['main']['TemplateController']['ListDocumentTemplates']();
}
