// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';

export function AddDispatchToMember(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function AllocateByTags(arg1:number):Promise<number>;

export function AllocateSingleTag(arg1:number,arg2:string,arg3:string):Promise<number>;

export function BindDefaultAddresses(arg1:number):Promise<Record<string, number>>;

export function CreateWave(arg1:string):Promise<model.Wave>;

export function DeleteWave(arg1:number):Promise<void>;

export function ExportOrderCSV(arg1:number,arg2:number):Promise<string>;

export function ImportDispatchWave(arg1:number,arg2:string,arg3:number):Promise<void>;

export function ImportToWave(arg1:number,arg2:string,arg3:number):Promise<void>;

export function ListDispatchRecords(arg1:number):Promise<Array<main.DispatchRecordItem>>;

export function ListWaves(arg1:string):Promise<Array<main.WaveItem>>;

export function PreviewExport(arg1:number):Promise<Record<string, number>>;

export function RemoveDispatchFromMember(arg1:number):Promise<void>;

export function RemoveProductFromWave(arg1:number,arg2:number):Promise<void>;

export function RemoveSingleTag(arg1:number,arg2:string,arg3:string):Promise<number>;

export function SetDispatchAddress(arg1:number,arg2:number,arg3:number):Promise<void>;

export function UpdateDispatchQuantity(arg1:number,arg2:number):Promise<void>;
