// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllocateByTags(arg1) {
  return window['go']['main']['WaveController']['AllocateByTags'](arg1);
}

export function BindDefaultAddresses(arg1) {
  return window['go']['main']['WaveController']['BindDefaultAddresses'](arg1);
}

export function CreateWave(arg1) {
  return window['go']['main']['WaveController']['CreateWave'](arg1);
}

export function DeleteWave(arg1) {
  return window['go']['main']['WaveController']['DeleteWave'](arg1);
}

export function ExportOrderCSV(arg1, arg2) {
  return window['go']['main']['WaveController']['ExportOrderCSV'](arg1, arg2);
}

export function ImportDispatchWave(arg1, arg2, arg3) {
  return window['go']['main']['WaveController']['ImportDispatchWave'](arg1, arg2, arg3);
}

export function ImportToWave(arg1, arg2, arg3) {
  return window['go']['main']['WaveController']['ImportToWave'](arg1, arg2, arg3);
}

export function ListDispatchRecords(arg1) {
  return window['go']['main']['WaveController']['ListDispatchRecords'](arg1);
}

export function ListWaves(arg1) {
  return window['go']['main']['WaveController']['ListWaves'](arg1);
}

export function PreviewExport(arg1) {
  return window['go']['main']['WaveController']['PreviewExport'](arg1);
}
