// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function AssignDemandToWave(arg1:number,arg2:number):Promise<void>;

export function CreateWave(arg1:dto.CreateWaveInput):Promise<dto.WaveDTO>;

export function GenerateParticipants(arg1:number):Promise<number>;

export function GetWave(arg1:number):Promise<dto.WaveDTO>;

export function GetWaveOverview(arg1:number):Promise<dto.WaveOverviewDTO>;

export function ListAssignedDemandsByWave(arg1:number):Promise<Array<dto.DemandDocumentDTO>>;

export function ListRecentHistory(arg1:number,arg2:number):Promise<Array<dto.HistoryNodeDTO>>;

export function ListWaves():Promise<Array<dto.WaveDTO>>;

export function MapDemandLines(arg1:number):Promise<dto.DemandMappingResult>;

export function RedoWaveAction(arg1:number):Promise<string>;

export function UndoWaveAction(arg1:number):Promise<string>;
